mod imdb;
mod tmdb;

use std::path::{Path, PathBuf};
use std::time::Duration;

use anyhow::{bail, Context, Result};
use clap::Parser;
use media_db::mime::VIDEO_EXTENSIONS;
use media_db::nameparse;
use serde::Deserialize;
use walkdir::WalkDir;

/// The first-line marker distinguishing our generated sidecars from
/// hand-written ones we must never clobber.
const MARKER: &str = "generated by media-enrich";

#[derive(Parser)]
#[command(about = "Writes Kodi-style .nfo sidecars for movies from TMDB. \
Re-runnable: by default only files missing an .nfo are enriched.")]
struct Args {
    /// The scanner's config file; its movies roots are enriched.
    #[arg(long, default_value = "media-scanner.toml")]
    config: PathBuf,
    /// TMDB API key (v3 key or v4 read token). Falls back to $TMDB_API_KEY.
    #[arg(long)]
    api_key: Option<String>,
    /// Also re-fetch .nfo files this tool generated earlier (data changes).
    #[arg(long)]
    refresh: bool,
    /// With --refresh: overwrite hand-written .nfo files too.
    #[arg(long)]
    force: bool,
    /// Show what would happen without any network calls or writes.
    #[arg(long)]
    dry_run: bool,
    /// Skip downloading poster images.
    #[arg(long)]
    no_posters: bool,
    /// Skip IMDb ratings.
    #[arg(long)]
    no_ratings: bool,
    /// Re-download the cached IMDb ratings dataset when older than this.
    #[arg(long, default_value_t = 7)]
    ratings_max_age_days: u64,
    /// Pause between movies, to stay polite to the API.
    #[arg(long, default_value_t = 300)]
    delay_ms: u64,
}

#[derive(Deserialize)]
struct ScannerConfig {
    roots: Vec<RootConfig>,
}

#[derive(Deserialize)]
struct RootConfig {
    path: PathBuf,
    kind: String,
}

#[derive(PartialEq, Clone, Copy)]
enum NfoState {
    Missing,
    Generated,
    HandWritten,
}

/// (state, whether the file already carries a <rating>).
fn nfo_state(nfo_path: &Path) -> (NfoState, bool) {
    match std::fs::read_to_string(nfo_path) {
        Err(_) => (NfoState::Missing, false),
        Ok(text) => {
            let has_rating = text.contains("<rating>");
            if text.contains(MARKER) {
                (NfoState::Generated, has_rating)
            } else {
                (NfoState::HandWritten, has_rating)
            }
        }
    }
}

/// "<stem>-poster.jpg" next to the media file (Kodi convention).
fn poster_path_for(media: &Path) -> PathBuf {
    let stem = media.file_stem().unwrap_or_default().to_string_lossy();
    media.with_file_name(format!("{stem}-poster.jpg"))
}

fn is_video(path: &Path) -> bool {
    path.extension()
        .and_then(|e| e.to_str())
        .map(|e| e.to_lowercase())
        .is_some_and(|e| VIDEO_EXTENSIONS.iter().any(|(known, _)| *known == e))
}

fn main() -> Result<()> {
    tracing_subscriber::fmt()
        .with_env_filter(
            tracing_subscriber::EnvFilter::try_from_default_env()
                .unwrap_or_else(|_| "info".into()),
        )
        .init();
    let args = Args::parse();

    let config: ScannerConfig = toml::from_str(
        &std::fs::read_to_string(&args.config)
            .with_context(|| format!("reading {}", args.config.display()))?,
    )
    .with_context(|| format!("parsing {}", args.config.display()))?;

    // Gather every movie file and decide what to do with it. A file needs
    // work when its .nfo is missing/refreshable or its poster is missing.
    struct Task {
        path: PathBuf,
        write_nfo: bool,
        write_poster: bool,
    }
    let mut tasks: Vec<Task> = Vec::new();
    let mut up_to_date = 0usize;
    let mut skipped_handwritten = 0usize;
    for root in config.roots.iter().filter(|r| r.kind == "movies") {
        if !root.path.is_dir() {
            tracing::warn!("movies root {} not accessible; skipping", root.path.display());
            continue;
        }
        for entry in WalkDir::new(&root.path)
            .follow_links(false)
            .into_iter()
            .filter_entry(|e| !e.file_name().to_string_lossy().starts_with('.'))
            .flatten()
            .filter(|e| e.file_type().is_file() && is_video(e.path()))
        {
            let path = entry.into_path();
            let (state, has_rating) = nfo_state(&path.with_extension("nfo"));
            let write_nfo = match state {
                NfoState::Missing => true,
                // A generated .nfo without a rating predates the ratings
                // feature; upgrade it in place.
                NfoState::Generated => args.refresh || (!has_rating && !args.no_ratings),
                NfoState::HandWritten => {
                    if args.refresh && !args.force {
                        skipped_handwritten += 1;
                    }
                    args.refresh && args.force
                }
            };
            let write_poster = !args.no_posters
                && (!poster_path_for(&path).exists()
                    || (args.refresh && state == NfoState::Generated));
            if write_nfo || write_poster {
                tasks.push(Task { path, write_nfo, write_poster });
            } else if state != NfoState::HandWritten || args.force {
                up_to_date += 1;
            }
        }
    }
    tasks.sort_by(|a, b| a.path.cmp(&b.path));

    // TV: group episodes by parsed series; one TMDB series lookup + one
    // call per season covers every episode.
    struct EpTask {
        path: PathBuf,
        season: i64,
        episode: i64,
    }
    struct SeriesPlan {
        name: String,
        episodes: Vec<EpTask>,          // episodes needing an .nfo
        poster_dest: Option<PathBuf>,   // series-folder poster to write
        loose_posters: Vec<PathBuf>,    // per-file posters for folderless episodes
    }
    let season_dir_re = regex::Regex::new(r"(?i)^(season[ ._-]*\d*|s\d{1,2})$").unwrap();
    let mut groups: std::collections::BTreeMap<String, (String, PathBuf, Vec<EpTask>, Vec<PathBuf>)> =
        Default::default();
    let mut tv_up_to_date = 0usize;
    for root in config.roots.iter().filter(|r| r.kind == "tv") {
        if !root.path.is_dir() {
            tracing::warn!("tv root {} not accessible; skipping", root.path.display());
            continue;
        }
        for entry in WalkDir::new(&root.path)
            .follow_links(false)
            .into_iter()
            .filter_entry(|e| !e.file_name().to_string_lossy().starts_with('.'))
            .flatten()
            .filter(|e| e.file_type().is_file() && is_video(e.path()))
        {
            let path = entry.into_path();
            let stem = path.file_stem().unwrap_or_default().to_string_lossy().to_string();
            let parent_dirs: Vec<&str> = path
                .strip_prefix(&root.path)
                .ok()
                .and_then(|rel| rel.parent())
                .map(|p| p.iter().filter_map(|c| c.to_str()).collect())
                .unwrap_or_default();
            let Some(parsed) = nameparse::episode(&stem, &parent_dirs) else { continue };

            let write_nfo = match nfo_state(&path.with_extension("nfo")).0 {
                NfoState::Missing => true,
                NfoState::Generated => args.refresh,
                NfoState::HandWritten => args.refresh && args.force,
            };
            // Series folder: the file's directory, or its parent when the
            // file sits in a season subfolder. The root itself is never a
            // series folder (loose files get per-file posters instead).
            let mut series_dir = path.parent().unwrap_or(&root.path).to_path_buf();
            if series_dir
                .file_name()
                .and_then(|n| n.to_str())
                .is_some_and(|n| season_dir_re.is_match(n))
            {
                series_dir = series_dir.parent().unwrap_or(&root.path).to_path_buf();
            }
            let loose = series_dir == root.path;

            let group = groups
                .entry(parsed.series.to_lowercase())
                .or_insert_with(|| (parsed.series.clone(), series_dir.clone(), Vec::new(), Vec::new()));
            if !loose {
                group.1 = series_dir;
            }
            if write_nfo {
                group.2.push(EpTask { path: path.clone(), season: parsed.season, episode: parsed.episode });
            } else {
                tv_up_to_date += 1;
            }
            if !args.no_posters && loose && (!poster_path_for(&path).exists() || args.refresh) {
                group.3.push(path);
            }
        }
    }
    let mut series_plans: Vec<SeriesPlan> = Vec::new();
    for (_, (name, series_dir, episodes, loose_posters)) in groups {
        let poster_file = series_dir.join("poster.jpg");
        let poster_dest = (!args.no_posters
            && series_dir.file_name().is_some()
            && !config.roots.iter().any(|r| r.path == series_dir)
            && (!poster_file.exists() || args.refresh))
        .then_some(poster_file);
        if !episodes.is_empty() || poster_dest.is_some() || !loose_posters.is_empty() {
            series_plans.push(SeriesPlan { name, episodes, poster_dest, loose_posters });
        }
    }

    println!(
        "movies: {} to enrich, {} up to date, {} hand-written .nfo (kept{})",
        tasks.len(),
        up_to_date,
        skipped_handwritten,
        if args.refresh && !args.force && skipped_handwritten > 0 {
            "; use --force to overwrite"
        } else {
            ""
        }
    );
    println!(
        "tv: {} series with work, {} episode .nfo up to date",
        series_plans.len(),
        tv_up_to_date
    );

    if args.dry_run {
        for task in &tasks {
            let stem = task.path.file_stem().unwrap_or_default().to_string_lossy();
            let (title, year) = nameparse::movie(&stem);
            let parts = match (task.write_nfo, task.write_poster) {
                (true, true) => "nfo+poster",
                (true, false) => "nfo",
                _ => "poster",
            };
            println!(
                "would enrich [{parts}]: {} -> \"{title}\"{}",
                task.path.display(),
                year.map(|y| format!(" ({y})")).unwrap_or_default()
            );
        }
        for plan in &series_plans {
            println!(
                "would enrich series \"{}\": {} episode .nfo{}{}",
                plan.name,
                plan.episodes.len(),
                if plan.poster_dest.is_some() { ", series poster" } else { "" },
                if plan.loose_posters.is_empty() {
                    String::new()
                } else {
                    format!(", {} loose-file poster(s)", plan.loose_posters.len())
                }
            );
        }
        return Ok(());
    }
    if tasks.is_empty() && series_plans.is_empty() {
        return Ok(());
    }

    let key = args
        .api_key
        .or_else(|| std::env::var("TMDB_API_KEY").ok())
        .filter(|k| !k.is_empty());
    let Some(key) = key else {
        bail!(
            "no TMDB API key: pass --api-key or set TMDB_API_KEY.\n\
             Get a free key at https://www.themoviedb.org/settings/api"
        );
    };
    let mut tmdb = tmdb::Tmdb::new(key);

    let mut nfos_written = 0usize;
    let mut posters_written = 0usize;
    let mut not_found: Vec<String> = Vec::new();
    // Movie .nfo writes are deferred until IMDb ratings are resolved (one
    // streaming pass over the dataset for all ids at once).
    let mut pending_nfos: Vec<(PathBuf, tmdb::MovieInfo, Option<String>)> = Vec::new();
    for (index, task) in tasks.iter().enumerate() {
        let stem = task.path.file_stem().unwrap_or_default().to_string_lossy();
        let (title, year) = nameparse::movie(&stem);
        match tmdb.find_movie(&title, year) {
            Ok(Some(info)) => {
                if task.write_nfo {
                    let imdb_id = if args.no_ratings {
                        None
                    } else {
                        tmdb.imdb_id(info.tmdb_id).unwrap_or_default()
                    };
                    pending_nfos.push((task.path.with_extension("nfo"), info.clone(), imdb_id));
                }
                let mut poster_note = "";
                if task.write_poster {
                    match &info.poster_path {
                        Some(remote) => {
                            tmdb.download_poster(remote, &poster_path_for(&task.path))?;
                            posters_written += 1;
                            poster_note = " +poster";
                        }
                        None => poster_note = " (no poster on TMDB)",
                    }
                }
                println!(
                    "[{}/{}] {} -> {} ({}) [{}]{poster_note}",
                    index + 1,
                    tasks.len(),
                    stem,
                    info.title,
                    info.year.map(|y| y.to_string()).unwrap_or_else(|| "?".into()),
                    info.genres.join(", ")
                );
            }
            Ok(None) => {
                println!("[{}/{}] {} -> no TMDB match", index + 1, tasks.len(), stem);
                not_found.push(task.path.display().to_string());
            }
            // A hard API failure (bad key, network down) aborts; per-title
            // misses do not.
            Err(err) => return Err(err.context(format!("looking up {stem:?}"))),
        }
        std::thread::sleep(Duration::from_millis(args.delay_ms));
    }

    // Resolve IMDb ratings for all pending movies in one dataset pass, then
    // flush the deferred .nfo writes. A dataset failure degrades to
    // rating-less sidecars rather than aborting.
    let needed: std::collections::HashSet<String> =
        pending_nfos.iter().filter_map(|(_, _, id)| id.clone()).collect();
    let ratings = if needed.is_empty() {
        Default::default()
    } else {
        imdb::ratings_for(&needed, args.ratings_max_age_days).unwrap_or_else(|err| {
            tracing::warn!("IMDb ratings unavailable ({err:#}); writing .nfo without ratings");
            Default::default()
        })
    };
    let mut rated = 0usize;
    for (nfo_path, info, imdb_id) in &pending_nfos {
        let rating = imdb_id.as_ref().and_then(|id| ratings.get(id)).copied();
        if rating.is_some() {
            rated += 1;
        }
        std::fs::write(nfo_path, render_nfo(info, rating))
            .with_context(|| format!("writing {}", nfo_path.display()))?;
        nfos_written += 1;
    }
    if !pending_nfos.is_empty() {
        println!("IMDb ratings attached: {rated}/{}", pending_nfos.len());
    }

    for plan in &series_plans {
        let info = match tmdb.find_series(&plan.name) {
            Ok(Some(info)) => info,
            Ok(None) => {
                println!("series \"{}\" -> no TMDB match", plan.name);
                not_found.push(format!("series: {}", plan.name));
                continue;
            }
            Err(err) => return Err(err.context(format!("looking up series {:?}", plan.name))),
        };
        std::thread::sleep(Duration::from_millis(args.delay_ms));

        let mut season_titles: std::collections::HashMap<i64, std::collections::HashMap<i64, String>> =
            Default::default();
        for ep in &plan.episodes {
            if !season_titles.contains_key(&ep.season) {
                let titles = tmdb.season_episode_titles(info.tmdb_id, ep.season)?;
                std::thread::sleep(Duration::from_millis(args.delay_ms));
                season_titles.insert(ep.season, titles);
            }
            let title = season_titles[&ep.season]
                .get(&ep.episode)
                .cloned()
                .unwrap_or_else(|| format!("Episode {}", ep.episode));
            let nfo_path = ep.path.with_extension("nfo");
            std::fs::write(
                &nfo_path,
                render_episode_nfo(&info.name, ep.season, ep.episode, &title),
            )
            .with_context(|| format!("writing {}", nfo_path.display()))?;
            nfos_written += 1;
        }

        let mut poster_note = String::new();
        if let Some(remote) = &info.poster_path {
            if let Some(dest) = &plan.poster_dest {
                tmdb.download_poster(remote, dest)?;
                posters_written += 1;
                poster_note = " +poster".into();
            }
            for path in &plan.loose_posters {
                tmdb.download_poster(remote, &poster_path_for(path))?;
                posters_written += 1;
                poster_note = " +poster".into();
            }
        }
        println!(
            "series {} -> {} ({} episode .nfo){poster_note}",
            plan.name,
            info.name,
            plan.episodes.len()
        );
    }

    println!(
        "\ndone: {nfos_written} .nfo files, {posters_written} posters written, {} without a match",
        not_found.len()
    );
    if !not_found.is_empty() {
        println!("no match (rename or hand-write an .nfo):");
        for path in not_found {
            println!("  {path}");
        }
    }
    Ok(())
}

fn xml_escape(s: &str) -> String {
    s.replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
}

fn render_episode_nfo(show: &str, season: i64, episode: i64, title: &str) -> String {
    format!(
        "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n\
         <!-- {MARKER} (TMDB) -->\n<episodedetails>\n\
         \x20 <showtitle>{}</showtitle>\n\
         \x20 <season>{season}</season>\n\
         \x20 <episode>{episode}</episode>\n\
         \x20 <title>{}</title>\n</episodedetails>\n",
        xml_escape(show),
        xml_escape(title)
    )
}

fn render_nfo(info: &tmdb::MovieInfo, rating: Option<f64>) -> String {
    let mut out = String::from("<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n");
    out.push_str(&format!("<!-- {MARKER} (TMDB) -->\n<movie>\n"));
    out.push_str(&format!("  <title>{}</title>\n", xml_escape(&info.title)));
    if let Some(year) = info.year {
        out.push_str(&format!("  <year>{year}</year>\n"));
    }
    if let Some(rating) = rating {
        out.push_str(&format!("  <rating>{rating:.1}</rating>\n"));
    }
    if let Some(plot) = &info.plot {
        out.push_str(&format!("  <plot>{}</plot>\n", xml_escape(plot)));
    }
    for genre in &info.genres {
        out.push_str(&format!("  <genre>{}</genre>\n", xml_escape(genre)));
    }
    for director in &info.directors {
        out.push_str(&format!("  <director>{}</director>\n", xml_escape(director)));
    }
    out.push_str(&format!(
        "  <uniqueid type=\"tmdb\" default=\"true\">{}</uniqueid>\n</movie>\n",
        info.tmdb_id
    ));
    out
}
