mod imdb;
mod remux;
mod subtitles;
mod tmdb;

use std::path::{Path, PathBuf};
use std::time::Duration;

use anyhow::{bail, Context, Result};
use clap::Parser;
use media_db::mime::VIDEO_EXTENSIONS;
use media_db::nameparse;
use serde::Deserialize;
use walkdir::WalkDir;

/// The first-line marker distinguishing our generated sidecars from
/// hand-written ones we must never clobber.
const MARKER: &str = "generated by media-enrich";

#[derive(Parser)]
#[command(about = "Writes Kodi-style .nfo sidecars for movies from TMDB. \
Re-runnable: by default only files missing an .nfo are enriched.")]
struct Args {
    /// The scanner's config file; its movies roots are enriched.
    #[arg(long, default_value = "media-scanner.toml")]
    config: PathBuf,
    /// TMDB API key (v3 key or v4 read token). Falls back to $TMDB_API_KEY.
    #[arg(long)]
    api_key: Option<String>,
    /// Also re-fetch .nfo files this tool generated earlier (data changes).
    #[arg(long)]
    refresh: bool,
    /// With --refresh: overwrite hand-written .nfo files too.
    #[arg(long)]
    force: bool,
    /// Show what would happen without any network calls or writes.
    #[arg(long)]
    dry_run: bool,
    /// Skip downloading poster images.
    #[arg(long)]
    no_posters: bool,
    /// Skip IMDb ratings.
    #[arg(long)]
    no_ratings: bool,
    /// Neutralize embedded container titles in video files (also enabled by
    /// strip_titles = true in the config's [enrich] section).
    #[arg(long)]
    strip_titles: bool,
    /// Embed same-name .srt sidecars into subtitle-less MP4s (also enabled by
    /// embed_subtitles = true in the config's [enrich] section).
    #[arg(long)]
    embed_subtitles: bool,
    /// Remux MKV files to MP4 (stream copy; AC-3/E-AC-3 audio gains a stereo
    /// AAC twin). Also enabled by remux_mkv = true in the [enrich] section.
    #[arg(long)]
    remux_mkv: bool,
    /// Re-download the cached IMDb ratings dataset when older than this.
    #[arg(long, default_value_t = 7)]
    ratings_max_age_days: u64,
    /// Pause between movies, to stay polite to the API.
    #[arg(long, default_value_t = 300)]
    delay_ms: u64,
}

#[derive(Deserialize)]
struct ScannerConfig {
    roots: Vec<RootConfig>,
    #[serde(default = "default_ffprobe")]
    ffprobe_path: String,
    #[serde(default)]
    enrich: EnrichSection,
}

fn default_ffprobe() -> String {
    "ffprobe".into()
}

/// The scanner's [enrich] section; only strip_titles concerns this tool,
/// the rest is read (and ignored here) so the shared config file parses.
#[derive(Deserialize, Default)]
struct EnrichSection {
    /// Neutralize scene-filename titles embedded in MP4/MKV containers, which
    /// players otherwise show in place of the catalog title during playback.
    /// Opt-in: this is the one enrichment step that writes into media files.
    #[serde(default)]
    strip_titles: bool,
    /// Embed a same-name .srt sidecar into MP4 files that have no subtitle
    /// stream (ffmpeg stream copy + mov_text; replaces the file atomically
    /// after verification). Opt-in.
    #[serde(default)]
    embed_subtitles: bool,
    /// Remux MKV files to MP4 for browser playback (stream copy, plus a
    /// stereo AAC twin ahead of any AC-3/E-AC-3 track; replaces the file
    /// after verification and removes the .mkv). Opt-in.
    #[serde(default)]
    remux_mkv: bool,
    #[serde(default = "default_ffmpeg")]
    ffmpeg_path: String,
    #[serde(flatten)]
    _rest: std::collections::HashMap<String, toml::Value>,
}

fn default_ffmpeg() -> String {
    "ffmpeg".into()
}

#[derive(Deserialize)]
struct RootConfig {
    path: PathBuf,
    kind: String,
}

#[derive(PartialEq, Clone, Copy, Debug)]
enum NfoState {
    Missing,
    Generated,
    HandWritten,
}

/// What an existing sidecar tells us before any lookup.
struct NfoProbe {
    state: NfoState,
    has_rating: bool,
    has_plot: bool,
    has_imdb: bool,
    has_set: bool,
    has_title: bool,
    /// `<uniqueid type="tmdb">` — the identity, when the sidecar names one.
    tmdb_id: Option<i64>,
}

impl NfoProbe {
    /// A hand-written sidecar that carries only a TMDB id and no title:
    /// the user's way of saying "this film, fill in the rest".
    fn is_pin(&self) -> bool {
        self.state == NfoState::HandWritten && self.tmdb_id.is_some() && !self.has_title
    }
}

fn nfo_state(nfo_path: &Path) -> NfoProbe {
    let text = std::fs::read_to_string(nfo_path).unwrap_or_default();
    let state = if text.is_empty() {
        NfoState::Missing
    } else if text.contains(MARKER) {
        NfoState::Generated
    } else {
        NfoState::HandWritten
    };
    NfoProbe {
        state,
        has_rating: text.contains("<rating>"),
        has_plot: text.contains("<plot>"),
        has_imdb: text.contains("type=\"imdb\""),
        has_set: text.contains("<set"),
        has_title: text.contains("<title>") || text.contains("<title "),
        tmdb_id: tmdb_uniqueid(&text),
    }
}

/// The numeric value of `<uniqueid type="tmdb" ...>NNN</uniqueid>`, if
/// present. Attribute order and quoting vary between writers (Kodi, tinyMediaManager,
/// a text editor), so this scans rather than parses.
fn tmdb_uniqueid(text: &str) -> Option<i64> {
    let mut rest = text;
    while let Some(start) = rest.find("<uniqueid") {
        let tag = &rest[start..];
        let close = tag.find('>')?;
        let attrs = &tag[..close];
        let body = &tag[close + 1..];
        let end = body.find('<').unwrap_or(body.len());
        let value = body[..end].trim();
        if (attrs.contains("type=\"tmdb\"") || attrs.contains("type='tmdb'")) && !value.is_empty() {
            return value.parse().ok();
        }
        rest = &tag[close + 1..];
    }
    None
}

/// Walk every video file in movie/tv roots and neutralize embedded
/// container titles. Read-only inspection first, so untitled files (the
/// vast majority) are never opened for writing.
fn strip_embedded_titles(config: &ScannerConfig) {
    use media_db::container::{self, TitleStatus};
    let mut stripped = 0usize;
    for root in config.roots.iter().filter(|r| r.kind == "movies" || r.kind == "tv") {
        if !root.path.is_dir() {
            continue;
        }
        for entry in WalkDir::new(&root.path)
            .follow_links(false)
            .into_iter()
            .filter_entry(|e| !e.file_name().to_string_lossy().starts_with('.'))
            .flatten()
            .filter(|e| e.file_type().is_file() && is_video(e.path()))
        {
            let path = entry.path();
            match container::inspect(path) {
                Ok(TitleStatus::Titles(_)) => match container::strip(path) {
                    Ok(removed) => {
                        for text in removed {
                            println!("stripped embedded title {text:?} from {}", path.display());
                            stripped += 1;
                        }
                    }
                    Err(err) => eprintln!("{}: could not strip title: {err:#}", path.display()),
                },
                Ok(_) => {}
                Err(err) => tracing::debug!("{}: title inspect failed: {err:#}", path.display()),
            }
        }
    }
    if stripped > 0 {
        println!("embedded titles stripped: {stripped}");
    }
}

/// Remux every eligible .mkv under the video roots to .mp4. Dry run:
/// probe and report only.
fn remux_mkv_files(config: &ScannerConfig, dry_run: bool) {
    let mut remuxed = 0usize;
    let mut planned = 0usize;
    let mut skipped: Vec<(PathBuf, String)> = Vec::new();
    for root in config.roots.iter().filter(|r| r.kind == "movies" || r.kind == "tv") {
        if !root.path.is_dir() {
            continue;
        }
        let mut paths: Vec<PathBuf> = WalkDir::new(&root.path)
            .follow_links(false)
            .into_iter()
            .filter_entry(|e| !e.file_name().to_string_lossy().starts_with('.'))
            .flatten()
            .filter(|e| e.file_type().is_file())
            .map(|e| e.into_path())
            .filter(|p| p.extension().and_then(|e| e.to_str()).is_some_and(|e| e.eq_ignore_ascii_case("mkv")))
            .collect();
        paths.sort();
        for path in paths {
            match remux::remux_if_applicable(&config.enrich.ffmpeg_path, &config.ffprobe_path, &path, dry_run) {
                Ok(remux::Outcome::WouldRemux(plan)) => {
                    planned += 1;
                    println!("would remux: {}{}", path.display(), describe_plan(&plan));
                }
                Ok(remux::Outcome::Remuxed(plan)) => {
                    remuxed += 1;
                    println!("remuxed to mp4: {}{}", path.display(), describe_plan(&plan));
                }
                Ok(remux::Outcome::Skipped(why)) => skipped.push((path, why)),
                Err(err) => eprintln!("{}: remux failed: {err:#}", path.display()),
            }
        }
    }
    if !skipped.is_empty() {
        println!("mkv kept as-is ({}):", skipped.len());
        for (path, why) in &skipped {
            println!("  {} — {why}", path.display());
        }
    }
    if dry_run {
        if planned > 0 {
            println!("(dry run) mkv files that would be remuxed: {planned}");
        }
    } else if remuxed > 0 {
        println!("mkv files remuxed to mp4: {remuxed}");
    }
}

fn describe_plan(plan: &remux::Plan) -> String {
    let mut out = String::new();
    match plan.twins() {
        0 => {}
        1 => out.push_str(" (+ stereo AAC twin for the AC-3/E-AC-3 track)"),
        n => out.push_str(&format!(" (+ stereo AAC twins for {n} AC-3/E-AC-3 tracks)")),
    }
    for note in &plan.notes {
        out.push_str(&format!(" [{note}]"));
    }
    out
}

/// Embed same-name .srt sidecars into MP4 files lacking a subtitle stream.
fn embed_sidecar_subtitles(config: &ScannerConfig) {
    let mut embedded = 0usize;
    for root in config.roots.iter().filter(|r| r.kind == "movies" || r.kind == "tv") {
        if !root.path.is_dir() {
            continue;
        }
        for entry in WalkDir::new(&root.path)
            .follow_links(false)
            .into_iter()
            .filter_entry(|e| !e.file_name().to_string_lossy().starts_with('.'))
            .flatten()
            .filter(|e| e.file_type().is_file() && is_video(e.path()))
        {
            let path = entry.path();
            // Cheap pre-check before spending an ffprobe call.
            if !path.with_extension("srt").is_file() {
                continue;
            }
            match subtitles::embed_if_applicable(
                &config.enrich.ffmpeg_path,
                &config.ffprobe_path,
                path,
            ) {
                Ok(subtitles::Outcome::Embedded) => {
                    println!("embedded subtitles into {}", path.display());
                    embedded += 1;
                }
                // "not mp4" and "already has subtitles" are the expected,
                // common skips; the rest mean an .srt exists but something
                // is off with it — surface those at the default log level.
                Ok(subtitles::Outcome::Skipped(why)) => {
                    if why == "not mp4" || why == "already has text subtitles" {
                        tracing::debug!("{}: subtitles not embedded ({why})", path.display());
                    } else {
                        println!("{}: subtitles not embedded ({why})", path.display());
                    }
                }
                Err(err) => eprintln!("{}: subtitle embedding failed: {err:#}", path.display()),
            }
        }
    }
    if embedded > 0 {
        println!("subtitle tracks embedded: {embedded}");
    }
}

/// "<stem>-poster.jpg" next to the media file (Kodi convention).
fn poster_path_for(media: &Path) -> PathBuf {
    let stem = media.file_stem().unwrap_or_default().to_string_lossy();
    media.with_file_name(format!("{stem}-poster.jpg"))
}

fn is_video(path: &Path) -> bool {
    path.extension()
        .and_then(|e| e.to_str())
        .map(|e| e.to_lowercase())
        .is_some_and(|e| VIDEO_EXTENSIONS.iter().any(|(known, _)| *known == e))
}

fn main() -> Result<()> {
    tracing_subscriber::fmt()
        .with_env_filter(
            tracing_subscriber::EnvFilter::try_from_default_env()
                .unwrap_or_else(|_| "info".into()),
        )
        .init();
    let args = Args::parse();

    let config: ScannerConfig = toml::from_str(
        &std::fs::read_to_string(&args.config)
            .with_context(|| format!("reading {}", args.config.display()))?,
    )
    .with_context(|| format!("parsing {}", args.config.display()))?;

    let do_strip = args.strip_titles || config.enrich.strip_titles;
    let do_subs = args.embed_subtitles || config.enrich.embed_subtitles;
    let do_remux = args.remux_mkv || config.enrich.remux_mkv;
    if args.dry_run {
        // Remux planning is probe-only, so the dry run can show it in full.
        if do_remux {
            remux_mkv_files(&config, true);
        }
        if do_strip {
            println!("(dry run: embedded-title stripping skipped)");
        }
        if do_subs {
            println!("(dry run: subtitle embedding skipped)");
        }
    } else {
        // Remux first so subtitle embedding sees the resulting MP4s, and
        // subtitles before titles so the title pass sees the final file.
        if do_remux {
            remux_mkv_files(&config, false);
        }
        if do_subs {
            embed_sidecar_subtitles(&config);
        }
        if do_strip {
            strip_embedded_titles(&config);
        }
    }

    // Gather every movie file and decide what to do with it. A file needs
    // work when its .nfo is missing/refreshable or its poster is missing.
    struct Task {
        path: PathBuf,
        write_nfo: bool,
        write_poster: bool,
        /// Identity fixed by the existing sidecar's TMDB id: no search.
        tmdb_id: Option<i64>,
    }
    let mut tasks: Vec<Task> = Vec::new();
    let mut up_to_date = 0usize;
    let mut skipped_handwritten = 0usize;
    let mut pinned = 0usize;
    for root in config.roots.iter().filter(|r| r.kind == "movies") {
        if !root.path.is_dir() {
            tracing::warn!("movies root {} not accessible; skipping", root.path.display());
            continue;
        }
        for entry in WalkDir::new(&root.path)
            .follow_links(false)
            .into_iter()
            .filter_entry(|e| !e.file_name().to_string_lossy().starts_with('.'))
            .flatten()
            .filter(|e| e.file_type().is_file() && is_video(e.path()))
        {
            let path = entry.into_path();
            let probe = nfo_state(&path.with_extension("nfo"));
            let state = probe.state;
            let write_nfo = match state {
                NfoState::Missing => true,
                // A generated .nfo missing a later-added field (rating,
                // imdb uniqueid, set) upgrades in place.
                NfoState::Generated => {
                    args.refresh
                        || (!probe.has_rating && !args.no_ratings)
                        || !probe.has_imdb
                        || !probe.has_set
                }
                // A pin is a request to fill in the sidecar; any other
                // hand-written .nfo is the user's and stays.
                NfoState::HandWritten if probe.is_pin() => {
                    pinned += 1;
                    true
                }
                NfoState::HandWritten => {
                    if args.refresh && !args.force {
                        skipped_handwritten += 1;
                    }
                    args.refresh && args.force
                }
            };
            let write_poster = !args.no_posters
                && (!poster_path_for(&path).exists()
                    || (args.refresh && state == NfoState::Generated));
            if write_nfo || write_poster {
                tasks.push(Task { path, write_nfo, write_poster, tmdb_id: probe.tmdb_id });
            } else if state != NfoState::HandWritten || args.force {
                up_to_date += 1;
            }
        }
    }
    tasks.sort_by(|a, b| a.path.cmp(&b.path));

    // TV: group episodes by parsed series; one TMDB series lookup + one
    // call per season covers every episode.
    struct EpTask {
        path: PathBuf,
        season: i64,
        episode: i64,
    }
    struct SeriesPlan {
        name: String,
        episodes: Vec<EpTask>,          // episodes needing an .nfo
        poster_dest: Option<PathBuf>,   // series-folder poster to write
        loose_posters: Vec<PathBuf>,    // per-file posters for folderless episodes
    }
    let season_dir_re = regex::Regex::new(r"(?i)^(season[ ._-]*\d*|s\d{1,2})$").unwrap();
    let mut groups: std::collections::BTreeMap<String, (String, PathBuf, Vec<EpTask>, Vec<PathBuf>)> =
        Default::default();
    let mut tv_up_to_date = 0usize;
    for root in config.roots.iter().filter(|r| r.kind == "tv") {
        if !root.path.is_dir() {
            tracing::warn!("tv root {} not accessible; skipping", root.path.display());
            continue;
        }
        for entry in WalkDir::new(&root.path)
            .follow_links(false)
            .into_iter()
            .filter_entry(|e| !e.file_name().to_string_lossy().starts_with('.'))
            .flatten()
            .filter(|e| e.file_type().is_file() && is_video(e.path()))
        {
            let path = entry.into_path();
            let stem = path.file_stem().unwrap_or_default().to_string_lossy().to_string();
            let parent_dirs: Vec<&str> = path
                .strip_prefix(&root.path)
                .ok()
                .and_then(|rel| rel.parent())
                .map(|p| p.iter().filter_map(|c| c.to_str()).collect())
                .unwrap_or_default();
            let Some(parsed) = nameparse::episode(&stem, &parent_dirs) else { continue };

            // A generated episode .nfo without a <plot> predates episode
            // overviews; upgrade it in place (like movie ratings).
            let probe = nfo_state(&path.with_extension("nfo"));
            let (ep_state, ep_has_plot, ep_has_imdb) = (probe.state, probe.has_plot, probe.has_imdb);
            let write_nfo = match ep_state {
                NfoState::Missing => true,
                NfoState::Generated => args.refresh || !ep_has_plot || !ep_has_imdb,
                NfoState::HandWritten => args.refresh && args.force,
            };
            // Series folder: the file's directory, or its parent when the
            // file sits in a season subfolder. The root itself is never a
            // series folder (loose files get per-file posters instead).
            let mut series_dir = path.parent().unwrap_or(&root.path).to_path_buf();
            if series_dir
                .file_name()
                .and_then(|n| n.to_str())
                .is_some_and(|n| season_dir_re.is_match(n))
            {
                series_dir = series_dir.parent().unwrap_or(&root.path).to_path_buf();
            }
            let loose = series_dir == root.path;

            let group = groups
                .entry(parsed.series.to_lowercase())
                .or_insert_with(|| (parsed.series.clone(), series_dir.clone(), Vec::new(), Vec::new()));
            if !loose {
                group.1 = series_dir;
            }
            if write_nfo {
                group.2.push(EpTask { path: path.clone(), season: parsed.season, episode: parsed.episode });
            } else {
                tv_up_to_date += 1;
            }
            if !args.no_posters && loose && (!poster_path_for(&path).exists() || args.refresh) {
                group.3.push(path);
            }
        }
    }
    let mut series_plans: Vec<SeriesPlan> = Vec::new();
    for (_, (name, series_dir, episodes, loose_posters)) in groups {
        let poster_file = series_dir.join("poster.jpg");
        let poster_dest = (!args.no_posters
            && series_dir.file_name().is_some()
            && !config.roots.iter().any(|r| r.path == series_dir)
            && (!poster_file.exists() || args.refresh))
        .then_some(poster_file);
        if !episodes.is_empty() || poster_dest.is_some() || !loose_posters.is_empty() {
            series_plans.push(SeriesPlan { name, episodes, poster_dest, loose_posters });
        }
    }

    println!(
        "movies: {} to enrich ({pinned} pinned by TMDB id), {} up to date, {} hand-written .nfo (kept{})",
        tasks.len(),
        up_to_date,
        skipped_handwritten,
        if args.refresh && !args.force && skipped_handwritten > 0 {
            "; use --force to overwrite"
        } else {
            ""
        }
    );
    println!(
        "tv: {} series with work, {} episode .nfo up to date",
        series_plans.len(),
        tv_up_to_date
    );

    if args.dry_run {
        for task in &tasks {
            let stem = task.path.file_stem().unwrap_or_default().to_string_lossy();
            let (title, year) = nameparse::movie(&stem);
            let parts = match (task.write_nfo, task.write_poster) {
                (true, true) => "nfo+poster",
                (true, false) => "nfo",
                _ => "poster",
            };
            match task.tmdb_id {
                Some(id) => println!(
                    "would enrich [{parts}]: {} -> TMDB id {id}",
                    task.path.display()
                ),
                None => println!(
                    "would enrich [{parts}]: {} -> \"{title}\"{}",
                    task.path.display(),
                    year.map(|y| format!(" ({y})")).unwrap_or_default()
                ),
            }
        }
        for plan in &series_plans {
            println!(
                "would enrich series \"{}\": {} episode .nfo{}{}",
                plan.name,
                plan.episodes.len(),
                if plan.poster_dest.is_some() { ", series poster" } else { "" },
                if plan.loose_posters.is_empty() {
                    String::new()
                } else {
                    format!(", {} loose-file poster(s)", plan.loose_posters.len())
                }
            );
        }
        return Ok(());
    }
    if tasks.is_empty() && series_plans.is_empty() {
        return Ok(());
    }

    let key = args
        .api_key
        .or_else(|| std::env::var("TMDB_API_KEY").ok())
        .filter(|k| !k.is_empty());
    let Some(key) = key else {
        bail!(
            "no TMDB API key: pass --api-key or set TMDB_API_KEY.\n\
             Get a free key at https://www.themoviedb.org/settings/api"
        );
    };
    let mut tmdb = tmdb::Tmdb::new(key);

    let mut nfos_written = 0usize;
    let mut posters_written = 0usize;
    let mut not_found: Vec<String> = Vec::new();
    // Movie .nfo writes are deferred until IMDb ratings are resolved (one
    // streaming pass over the dataset for all ids at once).
    let mut pending_nfos: Vec<(PathBuf, tmdb::MovieInfo, Option<String>)> = Vec::new();
    for (index, task) in tasks.iter().enumerate() {
        let stem = task.path.file_stem().unwrap_or_default().to_string_lossy();
        let (title, year) = nameparse::movie(&stem);
        // A sidecar that names a TMDB id (a user's pin, or our own earlier
        // match) settles the identity; searching is only for new files.
        let lookup = match task.tmdb_id {
            Some(id) => tmdb.movie_by_id(id),
            None => tmdb.find_movie(&title, year),
        };
        match lookup {
            Ok(Some(info)) => {
                if task.write_nfo {
                    let imdb_id = info.imdb_id.clone();
                    pending_nfos.push((task.path.with_extension("nfo"), info.clone(), imdb_id));
                }
                let mut poster_note = "";
                if task.write_poster {
                    match &info.poster_path {
                        Some(remote) => {
                            match tmdb.download_poster(remote, &poster_path_for(&task.path)) {
                                Ok(()) => {
                                    posters_written += 1;
                                    poster_note = " +poster";
                                }
                                // A single unwritable volume must not
                                // abort the whole run; retries cover it.
                                Err(err) => {
                                    eprintln!("{}: poster not written: {err:#}", task.path.display());
                                    poster_note = " (poster failed)";
                                }
                            }
                        }
                        None => poster_note = " (no poster on TMDB)",
                    }
                }
                println!(
                    "[{}/{}] {} -> {} ({}) [{}]{}{poster_note}",
                    index + 1,
                    tasks.len(),
                    stem,
                    info.title,
                    info.year.map(|y| y.to_string()).unwrap_or_else(|| "?".into()),
                    info.genres.join(", "),
                    if task.tmdb_id.is_some() { " (by id)" } else { "" }
                );
            }
            Ok(None) => {
                match task.tmdb_id {
                    Some(id) => println!(
                        "[{}/{}] {} -> TMDB has no movie with id {id} (check the pin)",
                        index + 1,
                        tasks.len(),
                        stem
                    ),
                    None => println!(
                        "[{}/{}] {} -> no TMDB match for \"{title}\"{}",
                        index + 1,
                        tasks.len(),
                        stem,
                        year.map(|y| format!(" ({y})")).unwrap_or_default()
                    ),
                }
                not_found.push(task.path.display().to_string());
            }
            // A hard API failure (bad key, network down) aborts; per-title
            // misses do not.
            Err(err) => return Err(err.context(format!("looking up {stem:?}"))),
        }
        std::thread::sleep(Duration::from_millis(args.delay_ms));
    }

    // Resolve IMDb ratings for all pending movies in one dataset pass, then
    // flush the deferred .nfo writes. A dataset failure degrades to
    // rating-less sidecars rather than aborting.
    let needed: std::collections::HashSet<String> =
        pending_nfos.iter().filter_map(|(_, _, id)| id.clone()).collect();
    let ratings = if needed.is_empty() {
        Default::default()
    } else {
        imdb::ratings_for(&needed, args.ratings_max_age_days).unwrap_or_else(|err| {
            tracing::warn!("IMDb ratings unavailable ({err:#}); writing .nfo without ratings");
            Default::default()
        })
    };
    let mut rated = 0usize;
    for (nfo_path, info, imdb_id) in &pending_nfos {
        let rating = imdb_id.as_ref().and_then(|id| ratings.get(id)).copied();
        if rating.is_some() {
            rated += 1;
        }
        match std::fs::write(nfo_path, render_nfo(info, rating, imdb_id.as_deref())) {
            Ok(()) => nfos_written += 1,
            Err(err) => eprintln!("{}: nfo not written: {err:#}", nfo_path.display()),
        }
    }
    if !pending_nfos.is_empty() {
        println!("IMDb ratings attached: {rated}/{}", pending_nfos.len());
    }

    // Episode .nfo writes are deferred like the movies': imdb ids are
    // collected first, then one pass over the (cached) ratings dataset
    // resolves all episode ratings at once.
    struct PendingEpisode {
        nfo_path: PathBuf,
        show: String,
        season: i64,
        episode: i64,
        title: String,
        plot: String,
        imdb_id: Option<String>,
    }
    let mut pending_episodes: Vec<PendingEpisode> = Vec::new();
    for plan in &series_plans {
        let info = match tmdb.find_series(&plan.name) {
            Ok(Some(info)) => info,
            Ok(None) => {
                println!("series \"{}\" -> no TMDB match", plan.name);
                not_found.push(format!("series: {}", plan.name));
                continue;
            }
            Err(err) => return Err(err.context(format!("looking up series {:?}", plan.name))),
        };
        std::thread::sleep(Duration::from_millis(args.delay_ms));

        let mut season_titles: std::collections::HashMap<
            i64,
            std::collections::HashMap<i64, (String, String)>,
        > = Default::default();
        for ep in &plan.episodes {
            if !season_titles.contains_key(&ep.season) {
                let titles = tmdb.season_episode_titles(info.tmdb_id, ep.season)?;
                std::thread::sleep(Duration::from_millis(args.delay_ms));
                season_titles.insert(ep.season, titles);
            }
            let (title, overview) = season_titles[&ep.season]
                .get(&ep.episode)
                .cloned()
                .unwrap_or_else(|| (format!("Episode {}", ep.episode), String::new()));
            let imdb_id = tmdb
                .episode_imdb_id(info.tmdb_id, ep.season, ep.episode)
                .unwrap_or_default();
            std::thread::sleep(Duration::from_millis(args.delay_ms / 3));
            pending_episodes.push(PendingEpisode {
                nfo_path: ep.path.with_extension("nfo"),
                show: info.name.clone(),
                season: ep.season,
                episode: ep.episode,
                title,
                plot: overview,
                imdb_id,
            });
        }

        let mut poster_note = String::new();
        if let Some(remote) = &info.poster_path {
            let mut poster_targets: Vec<PathBuf> = Vec::new();
            if let Some(dest) = &plan.poster_dest {
                poster_targets.push(dest.clone());
            }
            for path in &plan.loose_posters {
                poster_targets.push(poster_path_for(path));
            }
            for dest in poster_targets {
                match tmdb.download_poster(remote, &dest) {
                    Ok(()) => {
                        posters_written += 1;
                        poster_note = " +poster".into();
                    }
                    Err(err) => {
                        eprintln!("{}: poster not written: {err:#}", dest.display());
                        poster_note = " (poster failed)".into();
                    }
                }
            }
        }
        println!(
            "series {} -> {} ({} episode .nfo){poster_note}",
            plan.name,
            info.name,
            plan.episodes.len()
        );
    }

    if !pending_episodes.is_empty() {
        let needed: std::collections::HashSet<String> = pending_episodes
            .iter()
            .filter_map(|e| e.imdb_id.clone())
            .collect();
        let ep_ratings = if needed.is_empty() || args.no_ratings {
            Default::default()
        } else {
            imdb::ratings_for(&needed, args.ratings_max_age_days).unwrap_or_else(|err| {
                tracing::warn!("IMDb ratings unavailable ({err:#}); episode nfos written without");
                Default::default()
            })
        };
        let mut ep_rated = 0usize;
        for pe in &pending_episodes {
            let rating = pe.imdb_id.as_ref().and_then(|id| ep_ratings.get(id)).copied();
            if rating.is_some() {
                ep_rated += 1;
            }
            match std::fs::write(
                &pe.nfo_path,
                render_episode_nfo(
                    &pe.show, pe.season, pe.episode, &pe.title, &pe.plot,
                    rating, pe.imdb_id.as_deref(),
                ),
            ) {
                Ok(()) => nfos_written += 1,
                Err(err) => eprintln!("{}: nfo not written: {err:#}", pe.nfo_path.display()),
            }
        }
        println!(
            "episode IMDb ratings attached: {ep_rated}/{}",
            pending_episodes.len()
        );
    }

    println!(
        "\ndone: {nfos_written} .nfo files, {posters_written} posters written, {} without a match",
        not_found.len()
    );
    if !not_found.is_empty() {
        println!(
            "no match — rename, hand-write an .nfo, or pin the TMDB entry by saving\n\
             <movie><uniqueid type=\"tmdb\">ID</uniqueid></movie> as <stem>.nfo:"
        );
        for path in not_found {
            println!("  {path}");
        }
    }
    Ok(())
}

fn xml_escape(s: &str) -> String {
    s.replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
}

fn render_episode_nfo(
    show: &str,
    season: i64,
    episode: i64,
    title: &str,
    plot: &str,
    rating: Option<f64>,
    imdb_id: Option<&str>,
) -> String {
    // <plot> and the imdb uniqueid are always present (possibly empty) so
    // the upgrade checks can tell "TMDB has nothing" apart from "predates
    // the feature".
    let rating_line = rating
        .map(|r| format!("  <rating>{r:.1}</rating>\n"))
        .unwrap_or_default();
    format!(
        "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n\
         <!-- {MARKER} (TMDB) -->\n<episodedetails>\n\
         \x20 <showtitle>{}</showtitle>\n\
         \x20 <season>{season}</season>\n\
         \x20 <episode>{episode}</episode>\n\
         \x20 <title>{}</title>\n\
         \x20 <plot>{}</plot>\n{rating_line}\
         \x20 <uniqueid type=\"imdb\">{}</uniqueid>\n</episodedetails>\n",
        xml_escape(show),
        xml_escape(title),
        xml_escape(plot),
        xml_escape(imdb_id.unwrap_or(""))
    )
}

fn render_nfo(info: &tmdb::MovieInfo, rating: Option<f64>, imdb_id: Option<&str>) -> String {
    let mut out = String::from("<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n");
    out.push_str(&format!("<!-- {MARKER} (TMDB) -->\n<movie>\n"));
    out.push_str(&format!("  <title>{}</title>\n", xml_escape(&info.title)));
    if let Some(year) = info.year {
        out.push_str(&format!("  <year>{year}</year>\n"));
    }
    if let Some(rating) = rating {
        out.push_str(&format!("  <rating>{rating:.1}</rating>\n"));
    }
    if let Some(plot) = &info.plot {
        out.push_str(&format!("  <plot>{}</plot>\n", xml_escape(plot)));
    }
    for genre in &info.genres {
        out.push_str(&format!("  <genre>{}</genre>\n", xml_escape(genre)));
    }
    for director in &info.directors {
        out.push_str(&format!("  <director>{}</director>\n", xml_escape(director)));
    }
    // The set (TMDB collection) and imdb uniqueid are always written,
    // possibly empty, so the upgrade checks can tell "TMDB has nothing"
    // apart from "predates the feature". Flat <set> is Kodi's legacy form,
    // still read by everything.
    out.push_str(&format!(
        "  <set>{}</set>\n",
        xml_escape(info.collection.as_deref().unwrap_or(""))
    ));
    out.push_str(&format!(
        "  <uniqueid type=\"imdb\">{}</uniqueid>\n",
        xml_escape(imdb_id.unwrap_or(""))
    ));
    out.push_str(&format!(
        "  <uniqueid type=\"tmdb\" default=\"true\">{}</uniqueid>\n</movie>\n",
        info.tmdb_id
    ));
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn tmdb_uniqueid_reads_the_pin_form_and_kodi_forms() {
        assert_eq!(
            tmdb_uniqueid("<movie><uniqueid type=\"tmdb\">1304313</uniqueid></movie>"),
            Some(1304313)
        );
        // Our own generated form: attribute order and a default flag.
        assert_eq!(
            tmdb_uniqueid("  <uniqueid type=\"imdb\">tt0120616</uniqueid>\n  <uniqueid type=\"tmdb\" default=\"true\">564</uniqueid>\n"),
            Some(564)
        );
        assert_eq!(tmdb_uniqueid("<uniqueid default=\"true\" type='tmdb'> 42 </uniqueid>"), Some(42));
        // Only imdb, or an empty tmdb element: no identity.
        assert_eq!(tmdb_uniqueid("<uniqueid type=\"imdb\">tt0120616</uniqueid>"), None);
        assert_eq!(tmdb_uniqueid("<uniqueid type=\"tmdb\"></uniqueid>"), None);
        assert_eq!(tmdb_uniqueid("<movie><title>x</title></movie>"), None);
    }

    fn probe(text: &str) -> NfoProbe {
        let dir = std::env::temp_dir().join(format!("media-enrich-test-{}", std::process::id()));
        std::fs::create_dir_all(&dir).unwrap();
        let path = dir.join(format!("{}.nfo", text.len()));
        std::fs::write(&path, text).unwrap();
        let probe = nfo_state(&path);
        std::fs::remove_file(&path).ok();
        probe
    }

    #[test]
    fn pin_is_a_hand_written_sidecar_with_only_an_id() {
        let pin = probe("<movie><uniqueid type=\"tmdb\">1304313</uniqueid></movie>");
        assert_eq!(pin.state, NfoState::HandWritten);
        assert!(pin.is_pin());
        assert_eq!(pin.tmdb_id, Some(1304313));

        // A full hand-written sidecar that happens to carry the id is the
        // user's own and must not be rewritten.
        let full = probe("<movie><title>The Mummy</title><uniqueid type=\"tmdb\">1304313</uniqueid></movie>");
        assert!(!full.is_pin());
        assert_eq!(full.tmdb_id, Some(1304313));

        // Our generated sidecar: not a pin, but its id is the identity.
        let generated = probe(&format!("<!-- {MARKER} (TMDB) -->\n<movie><title>The Mummy</title><uniqueid type=\"tmdb\" default=\"true\">564</uniqueid></movie>"));
        assert_eq!(generated.state, NfoState::Generated);
        assert!(!generated.is_pin());
        assert_eq!(generated.tmdb_id, Some(564));

        assert_eq!(probe("").state, NfoState::Missing);
    }
}
