mod imdb;
mod loudness;
mod loudness_state;
mod remux;
mod captions_state;
mod subtitles;
mod tmdb;

use std::path::{Path, PathBuf};
use std::time::Duration;

use anyhow::{bail, Context, Result};
use captions_state::{CaptionsState, Stamp};
use loudness_state::LoudnessState;
use clap::Parser;
use media_db::mime::VIDEO_EXTENSIONS;
use media_db::nameparse;
use serde::Deserialize;
use walkdir::WalkDir;

/// The first-line marker distinguishing our generated sidecars from
/// hand-written ones we must never clobber.
const MARKER: &str = "generated by media-enrich";

#[derive(Parser)]
#[command(about = "Writes Kodi-style .nfo sidecars for movies from TMDB. \
Re-runnable: by default only files missing an .nfo are enriched.")]
struct Args {
    /// The scanner's config file; its movies roots are enriched.
    #[arg(long, default_value = "media-scanner.toml")]
    config: PathBuf,
    /// TMDB API key (v3 key or v4 read token). Falls back to $TMDB_API_KEY.
    #[arg(long)]
    api_key: Option<String>,
    /// Also re-fetch .nfo files this tool generated earlier (data changes).
    #[arg(long)]
    refresh: bool,
    /// With --refresh: overwrite hand-written .nfo files too.
    #[arg(long)]
    force: bool,
    /// Show what would happen without any network calls or writes.
    #[arg(long)]
    dry_run: bool,
    /// Skip downloading poster images.
    #[arg(long)]
    no_posters: bool,
    /// Skip IMDb ratings.
    #[arg(long)]
    no_ratings: bool,
    /// Neutralize embedded container titles in video files (also enabled by
    /// strip_titles = true in the config's [enrich] section).
    #[arg(long)]
    strip_titles: bool,
    /// Embed same-name .srt sidecars into subtitle-less MP4s, and re-embed
    /// when a sidecar embedded earlier has changed (also enabled by
    /// embed_subtitles = true in the config's [enrich] section).
    #[arg(long)]
    embed_subtitles: bool,
    /// Remux MKV files to MP4 (stream copy; AC-3/E-AC-3 audio gains a stereo
    /// AAC twin). Also enabled by remux_mkv = true in the [enrich] section.
    #[arg(long)]
    remux_mkv: bool,
    /// Skip extracting embedded text subtitle tracks to .srt sidecars (on
    /// by default; also disabled by extract_subtitles = false in [enrich]).
    #[arg(long)]
    no_extract_subtitles: bool,
    /// Leave hev1-tagged HEVC MP4s alone (on by default; also disabled by
    /// fix_hevc_tags = false in [enrich]). Normally they are retagged hvc1
    /// in place, which is what Safari, QuickTime and iOS need to play them.
    #[arg(long)]
    no_fix_hevc_tags: bool,
    /// With subtitle embedding: an MP4 whose single caption track carries no
    /// record and says something other than its .srt sidecar normally keeps
    /// its track; this says the sidecar wins and re-embeds it. A one-off for
    /// libraries whose sidecars were corrected before records existed.
    #[arg(long)]
    adopt_sidecar_captions: bool,
    /// Give newly arrived videos whose audio is mastered far below the
    /// rest a louder default track (a linear gain within the track's own
    /// headroom; the original stays behind it). Also enabled by
    /// normalize_loudness = true in the [enrich] section.
    #[arg(long)]
    normalize_loudness: bool,
    /// Measure (and, when it qualifies, normalize) this file or folder
    /// now, whenever it arrived. Repeatable. Works without
    /// --normalize-loudness, and with --dry-run to see the numbers only.
    #[arg(long, value_name = "PATH")]
    loudness_path: Vec<PathBuf>,
    /// Re-download the cached IMDb ratings dataset when older than this.
    #[arg(long, default_value_t = 7)]
    ratings_max_age_days: u64,
    /// Pause between movies, to stay polite to the API.
    #[arg(long, default_value_t = 300)]
    delay_ms: u64,
}

#[derive(Deserialize)]
struct ScannerConfig {
    roots: Vec<RootConfig>,
    /// Catalog location (shared with the scanner); the run lock lives
    /// beside it.
    db_path: Option<PathBuf>,
    #[serde(default = "default_ffprobe")]
    ffprobe_path: String,
    #[serde(default)]
    enrich: EnrichSection,
}

fn default_ffprobe() -> String {
    "ffprobe".into()
}

/// One media-enrich at a time. Two runs at once — the scanner's auto-run
/// alongside a manual one — would remux/embed the same files together,
/// each unlinking the other's temp output and wasting a full remux. The
/// lock file sits beside the catalog (already writable under the scanner
/// unit's sandbox) and is released by the OS when the process exits, so a
/// crash never leaves it stuck. The returned handle must stay alive for
/// the whole run.
fn acquire_run_lock(db_path: &Path) -> Result<std::fs::File> {
    let path = db_path.with_file_name("enrich.lock");
    if let Some(dir) = path.parent() {
        let _ = std::fs::create_dir_all(dir);
    }
    let file = std::fs::OpenOptions::new()
        .create(true)
        .write(true)
        .truncate(false)
        .open(&path)
        .with_context(|| format!("opening {}", path.display()))?;
    match file.try_lock() {
        Ok(()) => Ok(file),
        Err(std::fs::TryLockError::WouldBlock) => bail!(
            "another media-enrich run is in progress (holding {}); exiting",
            path.display()
        ),
        Err(std::fs::TryLockError::Error(err)) => {
            Err(err).with_context(|| format!("locking {}", path.display()))
        }
    }
}

/// The scanner's [enrich] section; only strip_titles concerns this tool,
/// the rest is read (and ignored here) so the shared config file parses.
#[derive(Deserialize, Default)]
struct EnrichSection {
    /// Neutralize scene-filename titles embedded in MP4/MKV containers, which
    /// players otherwise show in place of the catalog title during playback.
    /// Opt-in: this is the one enrichment step that writes into media files.
    #[serde(default)]
    strip_titles: bool,
    /// Embed a same-name .srt sidecar into MP4 files that have no subtitle
    /// stream (ffmpeg stream copy + mov_text; replaces the file atomically
    /// after verification). Opt-in.
    #[serde(default)]
    embed_subtitles: bool,
    /// Remux MKV files to MP4 for browser playback (stream copy, plus a
    /// stereo AAC twin ahead of any AC-3/E-AC-3 track; replaces the file
    /// after verification and removes the .mkv). Opt-in.
    #[serde(default)]
    remux_mkv: bool,
    /// Extract the best embedded text subtitle track of every video that
    /// has no .srt sidecar to `{stem}.srt`, ahead of playback. Only adds a
    /// sidecar; never touches media files. On by default.
    #[serde(default = "default_true")]
    extract_subtitles: bool,
    /// Retag hev1 HEVC video as hvc1 in place (a four-byte header patch,
    /// only when the header already carries the parameter sets), which
    /// Apple's players require. On by default.
    #[serde(default = "default_true")]
    fix_hevc_tags: bool,
    /// Add a louder default audio track to newly arrived videos mastered
    /// far below the target (see loudness.rs). Replaces the file after
    /// verification. Opt-in.
    #[serde(default)]
    normalize_loudness: bool,
    /// "YYYY-MM-DD": videos that entered the catalog on or after this
    /// day count as newly arrived. Unset: from this step's first run on.
    #[serde(default)]
    loudness_since: Option<String>,
    /// Integrated loudness quiet tracks are raised towards, LUFS.
    #[serde(default = "default_loudness_target")]
    loudness_target: f64,
    /// Raises smaller than this many dB are not worth a rewrite.
    #[serde(default = "default_loudness_min_gain")]
    loudness_min_gain: f64,
    #[serde(default = "default_ffmpeg")]
    ffmpeg_path: String,
    #[serde(flatten)]
    _rest: std::collections::HashMap<String, toml::Value>,
}

fn default_ffmpeg() -> String {
    "ffmpeg".into()
}

fn default_loudness_target() -> f64 {
    -24.0
}

fn default_loudness_min_gain() -> f64 {
    4.0
}

fn default_true() -> bool {
    true
}

#[derive(Deserialize)]
struct RootConfig {
    path: PathBuf,
    kind: String,
}

#[derive(PartialEq, Clone, Copy, Debug)]
enum NfoState {
    Missing,
    Generated,
    HandWritten,
}

/// What an existing sidecar tells us before any lookup.
struct NfoProbe {
    state: NfoState,
    has_rating: bool,
    has_plot: bool,
    has_imdb: bool,
    has_set: bool,
    has_title: bool,
    /// <aired> (episodes) / <premiered> (tvshow.nfo): air dates.
    has_aired: bool,
    has_premiered: bool,
    /// `<uniqueid type="tmdb">` — the identity, when the sidecar names one.
    tmdb_id: Option<i64>,
}

impl NfoProbe {
    /// A hand-written sidecar that carries only a TMDB id and no title:
    /// the user's way of saying "this film, fill in the rest".
    fn is_pin(&self) -> bool {
        self.state == NfoState::HandWritten && self.tmdb_id.is_some() && !self.has_title
    }
}

/// Every sidecar this tool writes goes through the atomic, symlink-refusing
/// writer: a half-written .nfo is never seen by the scanner, and a link
/// planted at the target path is never followed.
fn write_sidecar(path: &Path, text: String) -> std::io::Result<()> {
    media_db::sidecar::write_atomic(path, text.as_bytes())
}

fn nfo_state(nfo_path: &Path) -> NfoProbe {
    let text = media_db::sidecar::read_text_capped(nfo_path, media_db::sidecar::MAX_TEXT)
        .unwrap_or_default();
    let state = if text.is_empty() {
        NfoState::Missing
    } else if text.contains(MARKER) {
        NfoState::Generated
    } else {
        NfoState::HandWritten
    };
    NfoProbe {
        state,
        has_rating: text.contains("<rating>"),
        has_plot: text.contains("<plot>"),
        has_imdb: text.contains("type=\"imdb\""),
        has_set: text.contains("<set"),
        has_title: text.contains("<title>") || text.contains("<title "),
        has_aired: text.contains("<aired>") || text.contains("<aired/>"),
        has_premiered: text.contains("<premiered>") || text.contains("<premiered/>"),
        tmdb_id: tmdb_uniqueid(&text),
    }
}

/// The numeric value of `<uniqueid type="tmdb" ...>NNN</uniqueid>`, if
/// present. Attribute order and quoting vary between writers (Kodi, tinyMediaManager,
/// a text editor), so this scans rather than parses.
fn tmdb_uniqueid(text: &str) -> Option<i64> {
    let mut rest = text;
    while let Some(start) = rest.find("<uniqueid") {
        let tag = &rest[start..];
        let close = tag.find('>')?;
        let attrs = &tag[..close];
        let body = &tag[close + 1..];
        let end = body.find('<').unwrap_or(body.len());
        let value = body[..end].trim();
        if (attrs.contains("type=\"tmdb\"") || attrs.contains("type='tmdb'")) && !value.is_empty() {
            return value.parse().ok();
        }
        rest = &tag[close + 1..];
    }
    None
}

/// Walk every video file in movie/tv roots and neutralize embedded
/// container titles. Read-only inspection first, so untitled files (the
/// vast majority) are never opened for writing.
fn strip_embedded_titles(config: &ScannerConfig) {
    use media_db::container::{self, TitleStatus};
    let mut stripped = 0usize;
    for root in config.roots.iter().filter(|r| r.kind == "movies" || r.kind == "tv") {
        if !root.path.is_dir() {
            continue;
        }
        for entry in WalkDir::new(&root.path)
            .follow_links(false)
            .into_iter()
            .filter_entry(|e| !e.file_name().to_string_lossy().starts_with('.'))
            .flatten()
            .filter(|e| e.file_type().is_file() && is_video(e.path()))
        {
            let path = entry.path();
            match container::inspect(path) {
                Ok(TitleStatus::Titles(_)) => match container::strip(path) {
                    Ok(removed) => {
                        for text in removed {
                            println!("stripped embedded title {text:?} from {}", path.display());
                            stripped += 1;
                        }
                    }
                    Err(err) => eprintln!("{}: could not strip title: {err:#}", path.display()),
                },
                Ok(_) => {}
                Err(err) => tracing::debug!("{}: title inspect failed: {err:#}", path.display()),
            }
        }
    }
    if stripped > 0 {
        println!("embedded titles stripped: {stripped}");
    }
}

/// Retag hev1 HEVC MP4s as hvc1 in place so Apple's players accept them.
/// Header-only (moov parsed, four bytes written), so every video is
/// checked each run, like title stripping. Dry run: report only.
fn fix_hevc_tags(config: &ScannerConfig, dry_run: bool) {
    use media_db::container::{self, HevcTag};
    let (mut fixed, mut planned, mut stuck) = (0usize, 0usize, 0usize);
    for root in config.roots.iter().filter(|r| r.kind == "movies" || r.kind == "tv") {
        if !root.path.is_dir() {
            continue;
        }
        for entry in WalkDir::new(&root.path)
            .follow_links(false)
            .into_iter()
            .filter_entry(|e| !e.file_name().to_string_lossy().starts_with('.'))
            .flatten()
            .filter(|e| e.file_type().is_file() && is_video(e.path()))
        {
            let path = entry.path();
            match container::hevc_tag(path) {
                Ok(HevcTag::Hev1Fixable) if dry_run => {
                    println!("would retag HEVC hev1 as hvc1 in {}", path.display());
                    planned += 1;
                }
                Ok(HevcTag::Hev1Fixable) => match container::retag_hvc1(path) {
                    Ok(HevcTag::Hvc1) => {
                        println!("retagged HEVC hev1 as hvc1 (Apple-playable) in {}", path.display());
                        fixed += 1;
                    }
                    Ok(_) => {}
                    Err(err) => eprintln!("{}: could not retag: {err:#}", path.display()),
                },
                Ok(HevcTag::Hev1InBandOnly) => {
                    println!(
                        "{}: HEVC hev1 with in-band parameter sets only; Apple players will refuse it \
                         and only a remux (ffmpeg -c copy -tag:v hvc1) can fix it",
                        path.display()
                    );
                    stuck += 1;
                }
                Ok(_) => {}
                Err(err) => tracing::debug!("{}: HEVC tag check failed: {err:#}", path.display()),
            }
        }
    }
    if dry_run {
        if planned > 0 {
            println!("(dry run) HEVC files that would be retagged hvc1: {planned}");
        }
    } else if fixed > 0 {
        println!("HEVC files retagged hvc1: {fixed}");
    }
    if stuck > 0 {
        println!("HEVC files needing a remux for Apple playback: {stuck}");
    }
}

/// Extract embedded text subtitles to .srt sidecars wherever one is
/// missing. Dry run: probe and report only.
fn extract_embedded_subtitles(config: &ScannerConfig, dry_run: bool, captions: &mut CaptionsState) {
    let mut extracted = 0usize;
    let mut planned = 0usize;
    for root in config.roots.iter().filter(|r| r.kind == "movies" || r.kind == "tv") {
        if !root.path.is_dir() {
            continue;
        }
        for entry in WalkDir::new(&root.path)
            .follow_links(false)
            .into_iter()
            .filter_entry(|e| !e.file_name().to_string_lossy().starts_with('.'))
            .flatten()
            .filter(|e| e.file_type().is_file() && is_video(e.path()))
        {
            let path = entry.path();
            // Cheap pre-check before spending an ffprobe call.
            if path.with_extension("srt").exists() {
                continue;
            }
            match subtitles::extract_if_missing(
                &config.enrich.ffmpeg_path,
                &config.ffprobe_path,
                path,
                dry_run,
            ) {
                Ok(subtitles::ExtractOutcome::Extracted(track)) => {
                    println!(
                        "extracted subtitles (track {}: {}) to {}",
                        track.ordinal,
                        track.describe(),
                        path.with_extension("srt").display()
                    );
                    extracted += 1;
                    // Remember the pair as it now stands — the embed step
                    // need not probe a video for the sidecar it just got —
                    // and the extracted text as what the track says, so a
                    // later correction of this sidecar is recognised.
                    let srt = path.with_extension("srt");
                    let canonical = media_db::sidecar::read_capped(&srt, media_db::sidecar::MAX_TEXT)
                        .ok()
                        .and_then(|bytes| media_db::textenc::decode_subtitle_text(&bytes))
                        .map(|text| subtitles::sidecar_hash(&text));
                    if let (Some(m), Some(s)) = (Stamp::of(path), Stamp::of(&srt)) {
                        captions.record(path, m, s, "extracted", canonical.as_deref());
                    }
                }
                Ok(subtitles::ExtractOutcome::WouldExtract(track)) => {
                    println!(
                        "would extract subtitles (track {}: {}) from {}",
                        track.ordinal,
                        track.describe(),
                        path.display()
                    );
                    planned += 1;
                }
                Ok(subtitles::ExtractOutcome::Skipped(why)) => {
                    tracing::debug!("{}: subtitles not extracted ({why})", path.display());
                }
                Err(err) => eprintln!("{}: subtitle extraction failed: {err:#}", path.display()),
            }
        }
    }
    if dry_run {
        if planned > 0 {
            println!("(dry run) videos whose subtitles would be extracted: {planned}");
        }
    } else if extracted > 0 {
        println!("subtitle sidecars extracted: {extracted}");
    }
}

/// Is this one of our own temp outputs (`.{stem}.remux-tmp*.mp4`,
/// `.{stem}.subtitles-tmp*.mp4/.srt`)?
fn is_enrich_temp(name: &str) -> bool {
    name.starts_with('.')
        && (name.contains(".remux-tmp")
            || name.contains(".subtitles-tmp")
            || name.contains(".subtitles-extract")
            || name.contains(".loudness-tmp"))
}

/// Remove every temp output left under the video roots by earlier runs
/// (killed mid-mux, or the pre-lock era's colliding runs). Only called
/// with the run lock held, so none of them can still be in use.
fn remove_stale_temps(config: &ScannerConfig) {
    let mut removed = 0usize;
    for root in config.roots.iter().filter(|r| r.kind == "movies" || r.kind == "tv") {
        if !root.path.is_dir() {
            continue;
        }
        for entry in WalkDir::new(&root.path)
            .follow_links(false)
            .into_iter()
            // Hidden files are what we're after; hidden directories
            // (.Trash-*, .Spotlight-V100) are not ours to rummage in.
            .filter_entry(|e| e.file_type().is_file() || !e.file_name().to_string_lossy().starts_with('.'))
            .flatten()
            .filter(|e| e.file_type().is_file() && is_enrich_temp(&e.file_name().to_string_lossy()))
        {
            match std::fs::remove_file(entry.path()) {
                Ok(()) => {
                    println!("removed stale temp file {}", entry.path().display());
                    removed += 1;
                }
                Err(err) => eprintln!("{}: could not remove stale temp file: {err}", entry.path().display()),
            }
        }
    }
    if removed > 0 {
        println!("stale temp files removed: {removed}");
    }
}

/// Remux every eligible .mkv under the video roots to .mp4. Dry run:
/// probe and report only.
/// Returns the level of every stereo twin measured along the way, by the
/// new file's path, so the loudness step need not measure it again.
fn remux_mkv_files(
    config: &ScannerConfig,
    dry_run: bool,
    loudness: Option<&loudness::Policy>,
) -> Vec<(PathBuf, remux::TwinLevel)> {
    let mut twin_levels: Vec<(PathBuf, remux::TwinLevel)> = Vec::new();
    let mut remuxed = 0usize;
    let mut planned = 0usize;
    let mut skipped: Vec<(PathBuf, String)> = Vec::new();
    for root in config.roots.iter().filter(|r| r.kind == "movies" || r.kind == "tv") {
        if !root.path.is_dir() {
            continue;
        }
        let mut paths: Vec<PathBuf> = WalkDir::new(&root.path)
            .follow_links(false)
            .into_iter()
            .filter_entry(|e| !e.file_name().to_string_lossy().starts_with('.'))
            .flatten()
            .filter(|e| e.file_type().is_file())
            .map(|e| e.into_path())
            .filter(|p| p.extension().and_then(|e| e.to_str()).is_some_and(|e| e.eq_ignore_ascii_case("mkv")))
            .collect();
        paths.sort();
        for path in paths {
            match remux::remux_if_applicable(&config.enrich.ffmpeg_path, &config.ffprobe_path, &path, dry_run, loudness) {
                Ok(remux::Outcome::WouldRemux(plan)) => {
                    planned += 1;
                    println!("would remux: {}{}", path.display(), describe_plan(&plan));
                }
                Ok(remux::Outcome::Remuxed(plan)) => {
                    remuxed += 1;
                    println!("remuxed to mp4: {}{}", path.display(), describe_plan(&plan));
                    // The first twin is the default track: the one that counts.
                    if let Some(level) = plan.twin_levels.first() {
                        twin_levels.push((path.with_extension("mp4"), *level));
                    }
                }
                Ok(remux::Outcome::Skipped(why)) => skipped.push((path, why)),
                Err(err) => eprintln!("{}: remux failed: {err:#}", path.display()),
            }
        }
    }
    if !skipped.is_empty() {
        println!("mkv kept as-is ({}):", skipped.len());
        for (path, why) in &skipped {
            println!("  {} — {why}", path.display());
        }
    }
    if dry_run {
        if planned > 0 {
            println!("(dry run) mkv files that would be remuxed: {planned}");
        }
    } else if remuxed > 0 {
        println!("mkv files remuxed to mp4: {remuxed}");
    }
    twin_levels
}

/// "YYYY-MM-DD" as unix seconds at the start of that day (UTC).
fn parse_day(text: &str) -> Option<i64> {
    let mut parts = text.trim().splitn(3, '-');
    let y: i64 = parts.next()?.parse().ok()?;
    let m: i64 = parts.next()?.parse().ok()?;
    let d: i64 = parts.next()?.parse().ok()?;
    if !(1970..=9999).contains(&y) || !(1..=12).contains(&m) || !(1..=31).contains(&d) {
        return None;
    }
    // Days from the civil date (Howard Hinnant's algorithm).
    let y = if m <= 2 { y - 1 } else { y };
    let era = y.div_euclid(400);
    let yoe = y - era * 400;
    let doy = (153 * (if m > 2 { m - 3 } else { m + 9 }) + 2) / 5 + d - 1;
    let doe = yoe * 365 + yoe / 4 - yoe / 100 + doy;
    Some((era * 146_097 + doe - 719_468) * 86_400)
}

/// The containers the loudness step can rewrite.
fn is_loudness_candidate(path: &Path) -> bool {
    path.extension()
        .and_then(|e| e.to_str())
        .is_some_and(|e| ["mp4", "m4v", "mov", "mkv"].iter().any(|k| e.eq_ignore_ascii_case(k)))
}

fn video_files_under(dir: &Path) -> Vec<PathBuf> {
    let mut paths: Vec<PathBuf> = WalkDir::new(dir)
        .follow_links(false)
        .into_iter()
        .filter_entry(|e| !e.file_name().to_string_lossy().starts_with('.'))
        .flatten()
        .filter(|e| e.file_type().is_file() && is_loudness_candidate(e.path()))
        .map(|e| e.into_path())
        .collect();
    paths.sort();
    paths
}

/// What the loudness step is asked to do this run.
struct LoudnessJob<'a> {
    policy: loudness::Policy,
    /// Look at everything that arrived since the cutoff.
    auto: bool,
    /// Files and folders named on the command line: looked at whenever
    /// they arrived.
    explicit: &'a [PathBuf],
    dry_run: bool,
    /// Twins remux measured earlier in this run, by the new file's path.
    twin_levels: &'a [(PathBuf, remux::TwinLevel)],
}

/// Give quiet, newly arrived videos a raised default track (loudness.rs).
/// "Newly arrived" is the catalog's word: a file whose added-at is on or
/// after the cutoff, or that the scanner has not catalogued yet.
fn normalize_loudness(config: &ScannerConfig, job: &LoudnessJob, state: &mut LoudnessState) {
    let mut candidates: Vec<(PathBuf, bool)> = Vec::new();
    for path in job.explicit {
        if path.is_dir() {
            candidates.extend(video_files_under(path).into_iter().map(|p| (p, true)));
        } else if path.is_file() {
            candidates.push((path.clone(), true));
        } else {
            eprintln!("loudness: {} is not a file or folder", path.display());
        }
    }
    if job.auto {
        let now = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .map(|d| d.as_secs() as i64)
            .unwrap_or(0);
        let since = match config.enrich.loudness_since.as_deref() {
            Some(text) => parse_day(text).or_else(|| {
                eprintln!("loudness: loudness_since = {text:?} is not a YYYY-MM-DD date; automatic pass skipped");
                None
            }),
            None => {
                if !state.started() {
                    println!(
                        "loudness: media arriving from now on is measured; what is already here is left alone (set loudness_since in [enrich] to reach back, or name files with --loudness-path)"
                    );
                }
                Some(state.since_or_start(now))
            }
        };
        let db_path = config.db_path.clone().unwrap_or_else(media_db::open::default_db_path);
        let added = media_db::open_ro(&db_path)
            .and_then(|conn| media_db::queries::files::video_added_times(&conn));
        match (since, added) {
            (Some(since), Ok(added)) => {
                for root in config.roots.iter().filter(|r| (r.kind == "movies" || r.kind == "tv") && r.path.is_dir()) {
                    for path in video_files_under(&root.path) {
                        let arrived_since = added.get(&path).is_none_or(|t| *t >= since);
                        if arrived_since && !candidates.iter().any(|(p, _)| *p == path) {
                            candidates.push((path, false));
                        }
                    }
                }
            }
            (Some(_), Err(err)) => eprintln!(
                "loudness: the catalog could not be read ({err:#}), so new media cannot be told from old; automatic pass skipped"
            ),
            (None, _) => {}
        }
    }

    let (mut settled, mut looked, mut raised) = (0usize, 0usize, 0usize);
    for (path, named) in candidates {
        // A named file is always looked at; the rest only when new to
        // this step or changed since.
        if !named && state.settled(&path) {
            settled += 1;
            continue;
        }
        if let Some((_, level)) = job.twin_levels.iter().find(|(p, _)| *p == path) {
            let note = match level.gain {
                Some(_) => "stereo twin raised at remux",
                None => "stereo twin measured at remux: left as it is",
            };
            state.record(&path, note, Some(&level.measured), level.gain);
            continue;
        }
        looked += 1;
        let outcome = loudness::normalize_if_applicable(
            &config.enrich.ffmpeg_path, &config.ffprobe_path, &path, &job.policy, job.dry_run,
        );
        let shown = path.display();
        let (note, measured, gain): (String, Option<loudness::Measurement>, Option<f64>) = match outcome {
            Ok(loudness::Outcome::Skipped(why)) => {
                if named {
                    println!("loudness: {shown} — skipped: {why}");
                }
                (why, None, None)
            }
            Ok(loudness::Outcome::AlreadyNormalized) => {
                if named {
                    println!("loudness: {shown} — already carries a normalized track");
                }
                if !job.dry_run {
                    state.confirm_done(&path);
                }
                continue;
            }
            Ok(loudness::Outcome::Normal(m)) => {
                println!(
                    "loudness: {shown} — {:.1} LUFS, peak {:.1} dBTP: within range, left alone",
                    m.integrated, m.true_peak
                );
                ("within range".into(), Some(m), None)
            }
            Ok(loudness::Outcome::NoHeadroom { measured: m, wanted, headroom }) => {
                println!(
                    "loudness: {shown} — {:.1} LUFS would take {wanted:+.1} dB, but its peaks ({:.1} dBTP) leave {headroom:.1} dB: left alone (more would mean compressing the mix)",
                    m.integrated, m.true_peak
                );
                ("quiet, but no headroom for a linear raise".into(), Some(m), None)
            }
            Ok(loudness::Outcome::WouldNormalize { measured: m, gain }) => {
                println!(
                    "loudness: {shown} — {:.1} LUFS, peak {:.1} dBTP: would add a {gain:+.1} dB default track",
                    m.integrated, m.true_peak
                );
                continue;
            }
            Ok(loudness::Outcome::Normalized { before, after, gain }) => {
                raised += 1;
                println!(
                    "loudness: {shown} — {:.1} LUFS, peak {:.1} dBTP: added a {gain:+.1} dB default track (now {:.1} LUFS, peak {:.1} dBTP); the original follows it",
                    before.integrated, before.true_peak, after.integrated, after.true_peak
                );
                ("normalized".into(), Some(before), Some(gain))
            }
            Err(err) => {
                eprintln!("loudness: {shown} — failed: {err:#}");
                // Remembered like any other look: retried when the file
                // changes or is named, not on every run.
                (format!("failed: {err:#}"), None, None)
            }
        };
        if !job.dry_run {
            state.record(&path, &note, measured.as_ref(), gain);
        }
    }
    if looked > 0 || raised > 0 {
        println!(
            "loudness: {looked} looked at, {raised} given a raised track, {settled} unchanged since an earlier look{}",
            if job.dry_run { " (dry run)" } else { "" }
        );
    }
}

fn describe_plan(plan: &remux::Plan) -> String {
    let mut out = String::new();
    match plan.twins() {
        0 => {}
        1 => out.push_str(" (+ stereo AAC twin for the AC-3/E-AC-3 track)"),
        n => out.push_str(&format!(" (+ stereo AAC twins for {n} AC-3/E-AC-3 tracks)")),
    }
    for level in &plan.twin_levels {
        if let Some(gain) = level.gain {
            out.push_str(&format!(
                " [twin raised {gain:+.1} dB from {:.1} LUFS]",
                level.measured.integrated
            ));
        }
    }
    for note in &plan.notes {
        out.push_str(&format!(" [{note}]"));
    }
    out
}

/// Embed same-name .srt sidecars into MP4 files lacking a subtitle stream,
/// and replace captions embedded earlier whose sidecar has since changed.
fn embed_sidecar_subtitles(
    config: &ScannerConfig,
    dry_run: bool,
    adopt_all: bool,
    captions: &mut CaptionsState,
) {
    let (mut embedded, mut replaced, mut adopted, mut planned, mut unchanged) =
        (0usize, 0usize, 0usize, 0usize, 0usize);
    for root in config.roots.iter().filter(|r| r.kind == "movies" || r.kind == "tv") {
        if !root.path.is_dir() {
            continue;
        }
        for entry in WalkDir::new(&root.path)
            .follow_links(false)
            .into_iter()
            .filter_entry(|e| !e.file_name().to_string_lossy().starts_with('.'))
            .flatten()
            .filter(|e| e.file_type().is_file() && is_video(e.path()))
        {
            let path = entry.path();
            let srt = path.with_extension("srt");
            // Cheap pre-check before spending an ffprobe call.
            if !srt.is_file() {
                continue;
            }
            // Cheaper still: a pair that looks exactly as it did at the
            // last look (size and mtime of both files) would conclude the
            // same thing, so it is not read, hashed or probed again —
            // unless adopt-all is on and the pair has no provenance yet,
            // which is exactly the conclusion adopt-all changes.
            let known = captions.canonical_hash(path);
            if let (Some(m), Some(s)) = (Stamp::of(path), Stamp::of(&srt)) {
                if captions.unchanged(path, m, s) && !(adopt_all && known.is_none()) {
                    unchanged += 1;
                    continue;
                }
            }
            // (note for the memory, hash the track is now known to carry)
            let outcome: Option<(&str, Option<String>)> = match subtitles::embed_if_applicable(
                &config.enrich.ffmpeg_path,
                &config.ffprobe_path,
                path,
                dry_run,
                known.as_deref(),
                adopt_all,
            ) {
                Ok(subtitles::Outcome::Embedded(hash)) => {
                    println!("embedded subtitles into {}", path.display());
                    embedded += 1;
                    Some(("embedded", Some(hash)))
                }
                Ok(subtitles::Outcome::Replaced(hash)) => {
                    println!("replaced embedded captions from the updated sidecar in {}", path.display());
                    replaced += 1;
                    Some(("replaced", Some(hash)))
                }
                Ok(subtitles::Outcome::Adopted(hash)) => {
                    println!(
                        "{}: existing caption track matches the sidecar; sidecar adopted as its source",
                        path.display()
                    );
                    adopted += 1;
                    Some(("adopted", Some(hash)))
                }
                Ok(subtitles::Outcome::UpToDate(hash)) => {
                    tracing::debug!("{}: captions up to date", path.display());
                    Some(("captions up to date", Some(hash)))
                }
                Ok(subtitles::Outcome::WouldEmbed) => {
                    println!("would embed subtitles into {}", path.display());
                    planned += 1;
                    None
                }
                Ok(subtitles::Outcome::WouldReplace) => {
                    println!("would replace embedded captions (sidecar changed) in {}", path.display());
                    planned += 1;
                    None
                }
                // "not mp4" and "already has subtitles" are the expected,
                // common skips; the rest mean an .srt exists but something
                // is off with it — surface those at the default log level.
                Ok(subtitles::Outcome::Skipped(why)) => {
                    if why == "not mp4" || why == "already has text subtitles" {
                        tracing::debug!("{}: subtitles not embedded ({why})", path.display());
                    } else {
                        println!("{}: subtitles not embedded ({why})", path.display());
                    }
                    Some((why, None))
                }
                Err(err) => {
                    eprintln!("{}: subtitle embedding failed: {err:#}", path.display());
                    None
                }
            };
            // Recorded as the pair now stands (an embed just rewrote the
            // video). Dry runs and failures record nothing.
            if let Some((note, canonical)) = outcome.filter(|_| !dry_run) {
                if let (Some(m), Some(s)) = (Stamp::of(path), Stamp::of(&srt)) {
                    captions.record(path, m, s, note, canonical.as_deref());
                }
            }
        }
    }
    if unchanged > 0 {
        println!("caption pairs unchanged since the last look: {unchanged} (not probed)");
    }
    if dry_run {
        if planned > 0 {
            println!("(dry run) MP4s whose captions would be embedded or replaced: {planned}");
        }
    } else {
        if embedded > 0 {
            println!("subtitle tracks embedded: {embedded}");
        }
        if replaced > 0 {
            println!("embedded captions replaced from updated sidecars: {replaced}");
        }
        if adopted > 0 {
            println!("existing caption tracks adopted as sidecar-sourced: {adopted}");
        }
    }
}

/// "<stem>-poster.jpg" next to the media file (Kodi convention).
fn poster_path_for(media: &Path) -> PathBuf {
    let stem = media.file_stem().unwrap_or_default().to_string_lossy();
    media.with_file_name(format!("{stem}-poster.jpg"))
}

fn is_video(path: &Path) -> bool {
    path.extension()
        .and_then(|e| e.to_str())
        .map(|e| e.to_lowercase())
        .is_some_and(|e| VIDEO_EXTENSIONS.iter().any(|(known, _)| *known == e))
}

fn main() -> Result<()> {
    tracing_subscriber::fmt()
        .with_env_filter(
            tracing_subscriber::EnvFilter::try_from_default_env()
                .unwrap_or_else(|_| "info".into()),
        )
        .init();
    let args = Args::parse();

    let config: ScannerConfig = toml::from_str(
        &std::fs::read_to_string(&args.config)
            .with_context(|| format!("reading {}", args.config.display()))?,
    )
    .with_context(|| format!("parsing {}", args.config.display()))?;

    // Dry runs only probe, so they may overlap a real run.
    let _run_lock = if args.dry_run {
        None
    } else {
        Some(acquire_run_lock(
            &config.db_path.clone().unwrap_or_else(media_db::open::default_db_path),
        )?)
    };

    if _run_lock.is_some() {
        remove_stale_temps(&config);
    }

    // Memory for the caption steps (see captions_state), beside the catalog.
    let state_dir = config
        .db_path
        .clone()
        .unwrap_or_else(media_db::open::default_db_path)
        .parent()
        .map(Path::to_path_buf)
        .unwrap_or_else(|| PathBuf::from("."));
    let mut captions = CaptionsState::load(&state_dir);
    tracing::debug!("caption memory: {} pairs remembered", captions.len());

    let do_strip = args.strip_titles || config.enrich.strip_titles;
    let do_subs = args.embed_subtitles || config.enrich.embed_subtitles;
    let do_remux = args.remux_mkv || config.enrich.remux_mkv;
    let do_extract = !args.no_extract_subtitles && config.enrich.extract_subtitles;
    let do_hvc1 = !args.no_fix_hevc_tags && config.enrich.fix_hevc_tags;
    let do_loudness = args.normalize_loudness || config.enrich.normalize_loudness;
    let loudness_policy = loudness::Policy {
        target: config.enrich.loudness_target,
        min_gain: config.enrich.loudness_min_gain.max(1.0),
    };
    let mut loudness_state = LoudnessState::load(&state_dir);
    if args.dry_run {
        // Remux and extraction planning are probe-only, so the dry run can
        // show them in full.
        if do_remux {
            remux_mkv_files(&config, true, None);
        }
        if do_extract {
            extract_embedded_subtitles(&config, true, &mut captions);
        }
        if do_hvc1 {
            fix_hevc_tags(&config, true);
        }
        if do_strip {
            println!("(dry run: embedded-title stripping skipped)");
        }
        if do_subs {
            embed_sidecar_subtitles(&config, true, args.adopt_sidecar_captions, &mut captions);
        }
        // Measuring only reads, so a dry run shows the real numbers (at
        // the cost of decoding the audio of whatever is new).
        if do_loudness || !args.loudness_path.is_empty() {
            let job = LoudnessJob {
                policy: loudness_policy,
                auto: do_loudness,
                explicit: &args.loudness_path,
                dry_run: true,
                twin_levels: &[],
            };
            normalize_loudness(&config, &job, &mut loudness_state);
        }
    } else {
        // Remux first so subtitle embedding sees the resulting MP4s, and
        // subtitles before titles so the title pass sees the final file.
        // A stereo twin is an encode already: with loudness on, a quiet
        // one is raised as it is made.
        let twin_levels = if do_remux {
            remux_mkv_files(&config, false, do_loudness.then_some(&loudness_policy))
        } else {
            Vec::new()
        };
        if do_subs {
            embed_sidecar_subtitles(&config, false, args.adopt_sidecar_captions, &mut captions);
        }
        // After remux (the MP4 is what gets probed) and after embedding
        // (files that just gained a track from their sidecar keep it).
        if do_extract {
            extract_embedded_subtitles(&config, false, &mut captions);
        }
        // After the muxing steps (they write hvc1 themselves now): what is
        // left is what arrived hev1 and was never remuxed.
        if do_hvc1 {
            fix_hevc_tags(&config, false);
        }
        if do_strip {
            strip_embedded_titles(&config);
        }
        // Last, so the file it measures (and whose size and mtime it
        // remembers) is the one every other step has finished with.
        if do_loudness || !args.loudness_path.is_empty() {
            let job = LoudnessJob {
                policy: loudness_policy,
                auto: do_loudness,
                explicit: &args.loudness_path,
                dry_run: false,
                twin_levels: &twin_levels,
            };
            normalize_loudness(&config, &job, &mut loudness_state);
            loudness_state.forget_missing();
            if let Err(err) = loudness_state.save() {
                eprintln!("could not save the loudness memory: {err}");
            }
        }
        // Pairs the embed step did not meet under the roots it walked are
        // gone (video or sidecar removed); only that step meets every pair.
        if do_subs {
            let walked: Vec<PathBuf> = config
                .roots
                .iter()
                .filter(|r| (r.kind == "movies" || r.kind == "tv") && r.path.is_dir())
                .map(|r| r.path.clone())
                .collect();
            captions.forget_unseen_under(&walked);
        }
        if let Err(err) = captions.save() {
            eprintln!("could not save the caption memory: {err}");
        }
    }

    // Gather every movie file and decide what to do with it. A file needs
    // work when its .nfo is missing/refreshable or its poster is missing.
    struct Task {
        path: PathBuf,
        write_nfo: bool,
        write_poster: bool,
        /// Identity fixed by the existing sidecar's TMDB id: no search.
        tmdb_id: Option<i64>,
    }
    let mut tasks: Vec<Task> = Vec::new();
    let mut up_to_date = 0usize;
    let mut skipped_handwritten = 0usize;
    let mut pinned = 0usize;
    for root in config.roots.iter().filter(|r| r.kind == "movies") {
        if !root.path.is_dir() {
            tracing::warn!("movies root {} not accessible; skipping", root.path.display());
            continue;
        }
        for entry in WalkDir::new(&root.path)
            .follow_links(false)
            .into_iter()
            .filter_entry(|e| !e.file_name().to_string_lossy().starts_with('.'))
            .flatten()
            .filter(|e| e.file_type().is_file() && is_video(e.path()))
        {
            let path = entry.into_path();
            let probe = nfo_state(&path.with_extension("nfo"));
            let state = probe.state;
            let write_nfo = match state {
                NfoState::Missing => true,
                // A generated .nfo missing a later-added field (rating,
                // imdb uniqueid, set) upgrades in place.
                NfoState::Generated => {
                    args.refresh
                        || (!probe.has_rating && !args.no_ratings)
                        || !probe.has_imdb
                        || !probe.has_set
                }
                // A pin is a request to fill in the sidecar; any other
                // hand-written .nfo is the user's and stays.
                NfoState::HandWritten if probe.is_pin() => {
                    pinned += 1;
                    true
                }
                NfoState::HandWritten => {
                    if args.refresh && !args.force {
                        skipped_handwritten += 1;
                    }
                    args.refresh && args.force
                }
            };
            let write_poster = !args.no_posters
                && (!poster_path_for(&path).exists()
                    || (args.refresh && state == NfoState::Generated));
            if write_nfo || write_poster {
                tasks.push(Task { path, write_nfo, write_poster, tmdb_id: probe.tmdb_id });
            } else if state != NfoState::HandWritten || args.force {
                up_to_date += 1;
            }
        }
    }
    tasks.sort_by(|a, b| a.path.cmp(&b.path));

    // TV: group episodes by parsed series; one TMDB series lookup + one
    // call per season covers every episode.
    struct EpTask {
        path: PathBuf,
        season: i64,
        episode: i64,
    }
    struct SeriesPlan {
        name: String,
        episodes: Vec<EpTask>,          // episodes needing an .nfo
        poster_dest: Option<PathBuf>,   // series-folder poster to write
        loose_posters: Vec<PathBuf>,    // per-file posters for folderless episodes
        show_nfo_dest: Option<PathBuf>, // series-folder tvshow.nfo to write
        season_nfo_dests: Vec<(i64, PathBuf)>, // season-folder season.nfo to write
    }
    #[derive(Default)]
    struct SeriesAcc {
        name: String,
        series_dir: PathBuf,
        episodes: Vec<EpTask>,
        loose_posters: Vec<PathBuf>,
        /// Season subfolders seen, by season number.
        season_dirs: std::collections::BTreeMap<i64, PathBuf>,
    }
    let season_dir_re = regex::Regex::new(r"(?i)^(season[ ._-]*\d*|s\d{1,2})$").unwrap();
    let mut groups: std::collections::BTreeMap<String, SeriesAcc> = Default::default();
    let mut tv_up_to_date = 0usize;
    for root in config.roots.iter().filter(|r| r.kind == "tv") {
        if !root.path.is_dir() {
            tracing::warn!("tv root {} not accessible; skipping", root.path.display());
            continue;
        }
        for entry in WalkDir::new(&root.path)
            .follow_links(false)
            .into_iter()
            .filter_entry(|e| !e.file_name().to_string_lossy().starts_with('.'))
            .flatten()
            .filter(|e| e.file_type().is_file() && is_video(e.path()))
        {
            let path = entry.into_path();
            let stem = path.file_stem().unwrap_or_default().to_string_lossy().to_string();
            let parent_dirs: Vec<&str> = path
                .strip_prefix(&root.path)
                .ok()
                .and_then(|rel| rel.parent())
                .map(|p| p.iter().filter_map(|c| c.to_str()).collect())
                .unwrap_or_default();
            let Some(parsed) = nameparse::episode(&stem, &parent_dirs) else { continue };

            // A generated episode .nfo without a <plot>, an IMDb id or an
            // <aired> predates that feature; upgrade it in place (like
            // movie ratings).
            let probe = nfo_state(&path.with_extension("nfo"));
            let write_nfo = match probe.state {
                NfoState::Missing => true,
                NfoState::Generated => {
                    args.refresh || !probe.has_plot || !probe.has_imdb || !probe.has_aired
                }
                NfoState::HandWritten => args.refresh && args.force,
            };
            // Series folder: the file's directory, or its parent when the
            // file sits in a season subfolder. The root itself is never a
            // series folder (loose files get per-file posters instead).
            let mut series_dir = path.parent().unwrap_or(&root.path).to_path_buf();
            if series_dir
                .file_name()
                .and_then(|n| n.to_str())
                .is_some_and(|n| season_dir_re.is_match(n))
            {
                series_dir = series_dir.parent().unwrap_or(&root.path).to_path_buf();
            }
            let loose = series_dir == root.path;

            let group = groups.entry(parsed.series.to_lowercase()).or_insert_with(|| SeriesAcc {
                name: parsed.series.clone(),
                series_dir: series_dir.clone(),
                ..Default::default()
            });
            if !loose {
                group.series_dir = series_dir.clone();
            }
            if let Some(season_dir) = path.parent().filter(|p| *p != series_dir) {
                group
                    .season_dirs
                    .entry(parsed.season)
                    .or_insert_with(|| season_dir.to_path_buf());
            }
            if write_nfo {
                group.episodes.push(EpTask { path: path.clone(), season: parsed.season, episode: parsed.episode });
            } else {
                tv_up_to_date += 1;
            }
            if !args.no_posters && loose && (!poster_path_for(&path).exists() || args.refresh) {
                group.loose_posters.push(path);
            }
        }
    }
    let mut series_plans: Vec<SeriesPlan> = Vec::new();
    for (_, acc) in groups {
        let SeriesAcc { name, series_dir, episodes, loose_posters, season_dirs } = acc;
        let is_series_folder =
            series_dir.file_name().is_some() && !config.roots.iter().any(|r| r.path == series_dir);
        let poster_file = series_dir.join("poster.jpg");
        let poster_dest =
            (!args.no_posters && is_series_folder && (!poster_file.exists() || args.refresh))
                .then_some(poster_file);
        // Series-level tvshow.nfo (name, overview, IMDb id/rating), same
        // upgrade rules as episode sidecars: a generated one missing a
        // field predates the feature and is rewritten in place.
        let show_nfo = series_dir.join("tvshow.nfo");
        let show_probe = nfo_state(&show_nfo);
        let write_show_nfo = is_series_folder
            && match show_probe.state {
                NfoState::Missing => true,
                NfoState::Generated => {
                    args.refresh || !show_probe.has_plot || !show_probe.has_imdb || !show_probe.has_premiered
                }
                NfoState::HandWritten => args.refresh && args.force,
            };
        // Season-level season.nfo (the season's own TMDB overview), one
        // per season subfolder.
        let season_nfo_dests: Vec<(i64, PathBuf)> = season_dirs
            .into_iter()
            .filter(|(_, dir)| {
                let probe = nfo_state(&dir.join("season.nfo"));
                match probe.state {
                    NfoState::Missing => true,
                    NfoState::Generated => args.refresh || !probe.has_plot,
                    NfoState::HandWritten => args.refresh && args.force,
                }
            })
            .map(|(season, dir)| (season, dir.join("season.nfo")))
            .collect();
        if !episodes.is_empty()
            || poster_dest.is_some()
            || !loose_posters.is_empty()
            || write_show_nfo
            || !season_nfo_dests.is_empty()
        {
            series_plans.push(SeriesPlan {
                name,
                episodes,
                poster_dest,
                loose_posters,
                show_nfo_dest: write_show_nfo.then_some(show_nfo),
                season_nfo_dests,
            });
        }
    }

    println!(
        "movies: {} to enrich ({pinned} pinned by TMDB id), {} up to date, {} hand-written .nfo (kept{})",
        tasks.len(),
        up_to_date,
        skipped_handwritten,
        if args.refresh && !args.force && skipped_handwritten > 0 {
            "; use --force to overwrite"
        } else {
            ""
        }
    );
    println!(
        "tv: {} series with work, {} episode .nfo up to date",
        series_plans.len(),
        tv_up_to_date
    );

    if args.dry_run {
        for task in &tasks {
            let stem = task.path.file_stem().unwrap_or_default().to_string_lossy();
            let (title, year) = nameparse::movie(&stem);
            let parts = match (task.write_nfo, task.write_poster) {
                (true, true) => "nfo+poster",
                (true, false) => "nfo",
                _ => "poster",
            };
            match task.tmdb_id {
                Some(id) => println!(
                    "would enrich [{parts}]: {} -> TMDB id {id}",
                    task.path.display()
                ),
                None => println!(
                    "would enrich [{parts}]: {} -> \"{title}\"{}",
                    task.path.display(),
                    year.map(|y| format!(" ({y})")).unwrap_or_default()
                ),
            }
        }
        for plan in &series_plans {
            println!(
                "would enrich series \"{}\": {} episode .nfo{}{}{}{}",
                plan.name,
                plan.episodes.len(),
                if plan.show_nfo_dest.is_some() { ", tvshow.nfo" } else { "" },
                if plan.season_nfo_dests.is_empty() {
                    String::new()
                } else {
                    format!(", {} season.nfo", plan.season_nfo_dests.len())
                },
                if plan.poster_dest.is_some() { ", series poster" } else { "" },
                if plan.loose_posters.is_empty() {
                    String::new()
                } else {
                    format!(", {} loose-file poster(s)", plan.loose_posters.len())
                }
            );
        }
        return Ok(());
    }
    if tasks.is_empty() && series_plans.is_empty() {
        return Ok(());
    }

    let key = args
        .api_key
        .or_else(|| std::env::var("TMDB_API_KEY").ok())
        .filter(|k| !k.is_empty());
    let Some(key) = key else {
        bail!(
            "no TMDB API key: pass --api-key or set TMDB_API_KEY.\n\
             Get a free key at https://www.themoviedb.org/settings/api"
        );
    };
    let mut tmdb = tmdb::Tmdb::new(key);

    let mut nfos_written = 0usize;
    let mut posters_written = 0usize;
    let mut not_found: Vec<String> = Vec::new();
    // Movie .nfo writes are deferred until IMDb ratings are resolved (one
    // streaming pass over the dataset for all ids at once).
    let mut pending_nfos: Vec<(PathBuf, tmdb::MovieInfo, Option<String>)> = Vec::new();
    for (index, task) in tasks.iter().enumerate() {
        let stem = task.path.file_stem().unwrap_or_default().to_string_lossy();
        let (title, year) = nameparse::movie(&stem);
        // A sidecar that names a TMDB id (a user's pin, or our own earlier
        // match) settles the identity; searching is only for new files.
        let lookup = match task.tmdb_id {
            Some(id) => tmdb.movie_by_id(id),
            None => tmdb.find_movie(&title, year),
        };
        match lookup {
            Ok(Some(info)) => {
                if task.write_nfo {
                    let imdb_id = info.imdb_id.clone();
                    pending_nfos.push((task.path.with_extension("nfo"), info.clone(), imdb_id));
                }
                let mut poster_note = "";
                if task.write_poster {
                    match &info.poster_path {
                        Some(remote) => {
                            match tmdb.download_poster(remote, &poster_path_for(&task.path)) {
                                Ok(()) => {
                                    posters_written += 1;
                                    poster_note = " +poster";
                                }
                                // A single unwritable volume must not
                                // abort the whole run; retries cover it.
                                Err(err) => {
                                    eprintln!("{}: poster not written: {err:#}", task.path.display());
                                    poster_note = " (poster failed)";
                                }
                            }
                        }
                        None => poster_note = " (no poster on TMDB)",
                    }
                }
                println!(
                    "[{}/{}] {} -> {} ({}) [{}]{}{poster_note}",
                    index + 1,
                    tasks.len(),
                    stem,
                    info.title,
                    info.year.map(|y| y.to_string()).unwrap_or_else(|| "?".into()),
                    info.genres.join(", "),
                    if task.tmdb_id.is_some() { " (by id)" } else { "" }
                );
            }
            Ok(None) => {
                match task.tmdb_id {
                    Some(id) => println!(
                        "[{}/{}] {} -> TMDB has no movie with id {id} (check the pin)",
                        index + 1,
                        tasks.len(),
                        stem
                    ),
                    None => println!(
                        "[{}/{}] {} -> no TMDB match for \"{title}\"{}",
                        index + 1,
                        tasks.len(),
                        stem,
                        year.map(|y| format!(" ({y})")).unwrap_or_default()
                    ),
                }
                not_found.push(task.path.display().to_string());
            }
            // A hard API failure (bad key, network down) aborts; per-title
            // misses do not.
            Err(err) => return Err(err.context(format!("looking up {stem:?}"))),
        }
        std::thread::sleep(Duration::from_millis(args.delay_ms));
    }

    // Resolve IMDb ratings for all pending movies in one dataset pass, then
    // flush the deferred .nfo writes. A dataset failure degrades to
    // rating-less sidecars rather than aborting.
    let needed: std::collections::HashSet<String> =
        pending_nfos.iter().filter_map(|(_, _, id)| id.clone()).collect();
    let ratings = if needed.is_empty() {
        Default::default()
    } else {
        imdb::ratings_for(&needed, args.ratings_max_age_days).unwrap_or_else(|err| {
            tracing::warn!("IMDb ratings unavailable ({err:#}); writing .nfo without ratings");
            Default::default()
        })
    };
    let mut rated = 0usize;
    for (nfo_path, info, imdb_id) in &pending_nfos {
        let rating = imdb_id.as_ref().and_then(|id| ratings.get(id)).copied();
        if rating.is_some() {
            rated += 1;
        }
        match write_sidecar(nfo_path, render_nfo(info, rating, imdb_id.as_deref())) {
            Ok(()) => nfos_written += 1,
            Err(err) => eprintln!("{}: nfo not written: {err:#}", nfo_path.display()),
        }
    }
    if !pending_nfos.is_empty() {
        println!("IMDb ratings attached: {rated}/{}", pending_nfos.len());
    }

    // Episode .nfo writes are deferred like the movies': imdb ids are
    // collected first, then one pass over the (cached) ratings dataset
    // resolves all episode ratings at once.
    struct PendingEpisode {
        nfo_path: PathBuf,
        show: String,
        season: i64,
        episode: i64,
        title: String,
        plot: String,
        imdb_id: Option<String>,
        aired: Option<String>,
    }
    // Series tvshow.nfo writes are deferred like the episodes': the series
    // IMDb id joins the same ratings-dataset pass.
    struct PendingShow {
        nfo_path: PathBuf,
        name: String,
        plot: Option<String>,
        imdb_id: Option<String>,
        premiered: Option<String>,
    }
    let mut pending_episodes: Vec<PendingEpisode> = Vec::new();
    let mut pending_shows: Vec<PendingShow> = Vec::new();
    for plan in &series_plans {
        let info = match tmdb.find_series(&plan.name) {
            Ok(Some(info)) => info,
            Ok(None) => {
                println!("series \"{}\" -> no TMDB match", plan.name);
                not_found.push(format!("series: {}", plan.name));
                continue;
            }
            Err(err) => return Err(err.context(format!("looking up series {:?}", plan.name))),
        };
        std::thread::sleep(Duration::from_millis(args.delay_ms));

        let mut season_data: std::collections::HashMap<i64, tmdb::SeasonInfo> = Default::default();
        for ep in &plan.episodes {
            if !season_data.contains_key(&ep.season) {
                let data = tmdb.season_details(info.tmdb_id, ep.season)?;
                std::thread::sleep(Duration::from_millis(args.delay_ms));
                season_data.insert(ep.season, data);
            }
            let tmdb::EpisodeInfo { title, overview, aired } = season_data[&ep.season]
                .episodes
                .get(&ep.episode)
                .cloned()
                .unwrap_or_else(|| tmdb::EpisodeInfo {
                    title: format!("Episode {}", ep.episode),
                    overview: String::new(),
                    aired: None,
                });
            let imdb_id = tmdb
                .episode_imdb_id(info.tmdb_id, ep.season, ep.episode)
                .unwrap_or_default();
            std::thread::sleep(Duration::from_millis(args.delay_ms / 3));
            pending_episodes.push(PendingEpisode {
                nfo_path: ep.path.with_extension("nfo"),
                show: info.name.clone(),
                season: ep.season,
                episode: ep.episode,
                title,
                plot: overview,
                imdb_id,
                aired,
            });
        }

        // Season overviews ride the same per-season call the episode
        // titles come from; seasons with no episode work still get one.
        for (season, dest) in &plan.season_nfo_dests {
            if !season_data.contains_key(season) {
                let data = tmdb.season_details(info.tmdb_id, *season)?;
                std::thread::sleep(Duration::from_millis(args.delay_ms));
                season_data.insert(*season, data);
            }
            let overview = season_data[season].overview.as_deref().unwrap_or("");
            match write_sidecar(dest, render_season_nfo(&info.name, *season, overview)) {
                Ok(()) => nfos_written += 1,
                Err(err) => eprintln!("{}: nfo not written: {err:#}", dest.display()),
            }
        }
        if let Some(dest) = &plan.show_nfo_dest {
            pending_shows.push(PendingShow {
                nfo_path: dest.clone(),
                name: info.name.clone(),
                plot: info.plot.clone(),
                imdb_id: info.imdb_id.clone(),
                premiered: info.first_air_date.clone(),
            });
        }

        let mut poster_note = String::new();
        if let Some(remote) = &info.poster_path {
            let mut poster_targets: Vec<PathBuf> = Vec::new();
            if let Some(dest) = &plan.poster_dest {
                poster_targets.push(dest.clone());
            }
            for path in &plan.loose_posters {
                poster_targets.push(poster_path_for(path));
            }
            for dest in poster_targets {
                match tmdb.download_poster(remote, &dest) {
                    Ok(()) => {
                        posters_written += 1;
                        poster_note = " +poster".into();
                    }
                    Err(err) => {
                        eprintln!("{}: poster not written: {err:#}", dest.display());
                        poster_note = " (poster failed)".into();
                    }
                }
            }
        }
        println!(
            "series {} -> {} ({} episode .nfo){poster_note}",
            plan.name,
            info.name,
            plan.episodes.len()
        );
    }

    if !pending_episodes.is_empty() || !pending_shows.is_empty() {
        let needed: std::collections::HashSet<String> = pending_episodes
            .iter()
            .filter_map(|e| e.imdb_id.clone())
            .chain(pending_shows.iter().filter_map(|s| s.imdb_id.clone()))
            .collect();
        let ep_ratings = if needed.is_empty() || args.no_ratings {
            Default::default()
        } else {
            imdb::ratings_for(&needed, args.ratings_max_age_days).unwrap_or_else(|err| {
                tracing::warn!("IMDb ratings unavailable ({err:#}); episode nfos written without");
                Default::default()
            })
        };
        let mut ep_rated = 0usize;
        for pe in &pending_episodes {
            let rating = pe.imdb_id.as_ref().and_then(|id| ep_ratings.get(id)).copied();
            if rating.is_some() {
                ep_rated += 1;
            }
            match write_sidecar(
                &pe.nfo_path,
                render_episode_nfo(
                    &pe.show, pe.season, pe.episode, &pe.title, &pe.plot,
                    rating, pe.imdb_id.as_deref(), pe.aired.as_deref(),
                ),
            ) {
                Ok(()) => nfos_written += 1,
                Err(err) => eprintln!("{}: nfo not written: {err:#}", pe.nfo_path.display()),
            }
        }
        if !pending_episodes.is_empty() {
            println!(
                "episode IMDb ratings attached: {ep_rated}/{}",
                pending_episodes.len()
            );
        }
        for show in &pending_shows {
            let rating = show.imdb_id.as_ref().and_then(|id| ep_ratings.get(id)).copied();
            match write_sidecar(
                &show.nfo_path,
                render_show_nfo(
                    &show.name, show.plot.as_deref(), rating, show.imdb_id.as_deref(),
                    show.premiered.as_deref(),
                ),
            ) {
                Ok(()) => nfos_written += 1,
                Err(err) => eprintln!("{}: nfo not written: {err:#}", show.nfo_path.display()),
            }
        }
    }

    println!(
        "\ndone: {nfos_written} .nfo files, {posters_written} posters written, {} without a match",
        not_found.len()
    );
    if !not_found.is_empty() {
        println!(
            "no match — rename, hand-write an .nfo, or pin the TMDB entry by saving\n\
             <movie><uniqueid type=\"tmdb\">ID</uniqueid></movie> as <stem>.nfo:"
        );
        for path in not_found {
            println!("  {path}");
        }
    }
    Ok(())
}

fn xml_escape(s: &str) -> String {
    s.replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
}

/// Series-level tvshow.nfo (Kodi convention: sits in the series folder).
/// <plot>, <premiered> and the imdb uniqueid are always present (possibly
/// empty) so the upgrade checks can tell "TMDB has nothing" apart from
/// "predates the feature" — same convention as the episode sidecars.
fn render_show_nfo(
    name: &str,
    plot: Option<&str>,
    rating: Option<f64>,
    imdb_id: Option<&str>,
    premiered: Option<&str>,
) -> String {
    let rating_line = rating
        .map(|r| format!("  <rating>{r:.1}</rating>\n"))
        .unwrap_or_default();
    format!(
        "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n\
         <!-- {MARKER} (TMDB) -->\n<tvshow>\n\
         \x20 <title>{}</title>\n\
         \x20 <plot>{}</plot>\n\
         \x20 <premiered>{}</premiered>\n{rating_line}\
         \x20 <uniqueid type=\"imdb\">{}</uniqueid>\n</tvshow>\n",
        xml_escape(name),
        xml_escape(plot.unwrap_or("")),
        xml_escape(premiered.unwrap_or("")),
        xml_escape(imdb_id.unwrap_or(""))
    )
}

/// Season-level season.nfo (Kodi convention: sits in the season folder).
/// <showtitle> is included so the scanner can key the season without
/// guessing from directory names.
fn render_season_nfo(show: &str, season: i64, plot: &str) -> String {
    format!(
        "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n\
         <!-- {MARKER} (TMDB) -->\n<season>\n\
         \x20 <showtitle>{}</showtitle>\n\
         \x20 <seasonnumber>{season}</seasonnumber>\n\
         \x20 <plot>{}</plot>\n</season>\n",
        xml_escape(show),
        xml_escape(plot)
    )
}

fn render_episode_nfo(
    show: &str,
    season: i64,
    episode: i64,
    title: &str,
    plot: &str,
    rating: Option<f64>,
    imdb_id: Option<&str>,
    aired: Option<&str>,
) -> String {
    // <plot>, <aired> and the imdb uniqueid are always present (possibly
    // empty) so the upgrade checks can tell "TMDB has nothing" apart from
    // "predates the feature".
    let rating_line = rating
        .map(|r| format!("  <rating>{r:.1}</rating>\n"))
        .unwrap_or_default();
    format!(
        "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n\
         <!-- {MARKER} (TMDB) -->\n<episodedetails>\n\
         \x20 <showtitle>{}</showtitle>\n\
         \x20 <season>{season}</season>\n\
         \x20 <episode>{episode}</episode>\n\
         \x20 <title>{}</title>\n\
         \x20 <aired>{}</aired>\n\
         \x20 <plot>{}</plot>\n{rating_line}\
         \x20 <uniqueid type=\"imdb\">{}</uniqueid>\n</episodedetails>\n",
        xml_escape(show),
        xml_escape(title),
        xml_escape(aired.unwrap_or("")),
        xml_escape(plot),
        xml_escape(imdb_id.unwrap_or(""))
    )
}

fn render_nfo(info: &tmdb::MovieInfo, rating: Option<f64>, imdb_id: Option<&str>) -> String {
    let mut out = String::from("<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n");
    out.push_str(&format!("<!-- {MARKER} (TMDB) -->\n<movie>\n"));
    out.push_str(&format!("  <title>{}</title>\n", xml_escape(&info.title)));
    if let Some(year) = info.year {
        out.push_str(&format!("  <year>{year}</year>\n"));
    }
    if let Some(rating) = rating {
        out.push_str(&format!("  <rating>{rating:.1}</rating>\n"));
    }
    if let Some(plot) = &info.plot {
        out.push_str(&format!("  <plot>{}</plot>\n", xml_escape(plot)));
    }
    for genre in &info.genres {
        out.push_str(&format!("  <genre>{}</genre>\n", xml_escape(genre)));
    }
    for director in &info.directors {
        out.push_str(&format!("  <director>{}</director>\n", xml_escape(director)));
    }
    // The set (TMDB collection) and imdb uniqueid are always written,
    // possibly empty, so the upgrade checks can tell "TMDB has nothing"
    // apart from "predates the feature". Flat <set> is Kodi's legacy form,
    // still read by everything.
    out.push_str(&format!(
        "  <set>{}</set>\n",
        xml_escape(info.collection.as_deref().unwrap_or(""))
    ));
    out.push_str(&format!(
        "  <uniqueid type=\"imdb\">{}</uniqueid>\n",
        xml_escape(imdb_id.unwrap_or(""))
    ));
    out.push_str(&format!(
        "  <uniqueid type=\"tmdb\" default=\"true\">{}</uniqueid>\n</movie>\n",
        info.tmdb_id
    ));
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn tmdb_uniqueid_reads_the_pin_form_and_kodi_forms() {
        assert_eq!(
            tmdb_uniqueid("<movie><uniqueid type=\"tmdb\">1304313</uniqueid></movie>"),
            Some(1304313)
        );
        // Our own generated form: attribute order and a default flag.
        assert_eq!(
            tmdb_uniqueid("  <uniqueid type=\"imdb\">tt0120616</uniqueid>\n  <uniqueid type=\"tmdb\" default=\"true\">564</uniqueid>\n"),
            Some(564)
        );
        assert_eq!(tmdb_uniqueid("<uniqueid default=\"true\" type='tmdb'> 42 </uniqueid>"), Some(42));
        // Only imdb, or an empty tmdb element: no identity.
        assert_eq!(tmdb_uniqueid("<uniqueid type=\"imdb\">tt0120616</uniqueid>"), None);
        assert_eq!(tmdb_uniqueid("<uniqueid type=\"tmdb\"></uniqueid>"), None);
        assert_eq!(tmdb_uniqueid("<movie><title>x</title></movie>"), None);
    }

    #[test]
    fn air_dates_are_written_and_their_absence_marks_an_upgrade() {
        let ep = render_episode_nfo("Show", 1, 2, "Pilot", "About.", Some(8.1), Some("tt0000002"), Some("2000-10-15"));
        assert!(ep.contains("<aired>2000-10-15</aired>"));
        assert!(probe(&ep).has_aired);
        let ep_undated = render_episode_nfo("Show", 1, 2, "Pilot", "About.", None, None, None);
        assert!(ep_undated.contains("<aired></aired>"), "present but empty: TMDB had none");
        assert!(probe(&ep_undated).has_aired, "an empty tag still counts as written");
        assert!(!probe("<!-- generated by media-enrich (TMDB) -->\n<episodedetails><title>x</title><plot>p</plot><uniqueid type=\"imdb\">tt0000001</uniqueid></episodedetails>").has_aired);

        let show = render_show_nfo("Show", Some("p"), None, Some("tt0000003"), Some("2000-10-15"));
        assert!(show.contains("<premiered>2000-10-15</premiered>"));
        assert!(probe(&show).has_premiered);
        assert!(!probe("<tvshow><title>x</title><plot>p</plot></tvshow>").has_premiered);
    }

    fn probe(text: &str) -> NfoProbe {
        let dir = std::env::temp_dir().join(format!("media-enrich-test-{}", std::process::id()));
        std::fs::create_dir_all(&dir).unwrap();
        let path = dir.join(format!("{}.nfo", text.len()));
        std::fs::write(&path, text).unwrap();
        let probe = nfo_state(&path);
        std::fs::remove_file(&path).ok();
        probe
    }

    #[test]
    fn pin_is_a_hand_written_sidecar_with_only_an_id() {
        let pin = probe("<movie><uniqueid type=\"tmdb\">1304313</uniqueid></movie>");
        assert_eq!(pin.state, NfoState::HandWritten);
        assert!(pin.is_pin());
        assert_eq!(pin.tmdb_id, Some(1304313));

        // A full hand-written sidecar that happens to carry the id is the
        // user's own and must not be rewritten.
        let full = probe("<movie><title>The Mummy</title><uniqueid type=\"tmdb\">1304313</uniqueid></movie>");
        assert!(!full.is_pin());
        assert_eq!(full.tmdb_id, Some(1304313));

        // Our generated sidecar: not a pin, but its id is the identity.
        let generated = probe(&format!("<!-- {MARKER} (TMDB) -->\n<movie><title>The Mummy</title><uniqueid type=\"tmdb\" default=\"true\">564</uniqueid></movie>"));
        assert_eq!(generated.state, NfoState::Generated);
        assert!(!generated.is_pin());
        assert_eq!(generated.tmdb_id, Some(564));

        assert_eq!(probe("").state, NfoState::Missing);
    }
}
