[package]
name = "media-server"
version.workspace = true
edition.workspace = true

[dependencies]
media-db = { path = "../media-db" }

anyhow.workspace = true
axum = "0.8"
base64.workspace = true
clap.workspace = true
if-addrs = "0.13"
lofty = "0.21"
quick-xml.workspace = true
rusqlite.workspace = true
serde.workspace = true
socket2 = { version = "0.5", features = ["all"] }
tokio = { version = "1", features = ["macros", "process", "rt-multi-thread", "net", "signal", "sync", "time"] }
toml.workspace = true
tower = { version = "0.5", features = ["util"] }
tower-http = { version = "0.6", features = ["fs", "trace"] }
tracing.workspace = true
tracing-subscriber.workspace = true
uuid.workspace = true
