[package]
name = "media-server"
version.workspace = true
edition.workspace = true

[dependencies]
media-db = { path = "../media-db" }

anyhow.workspace = true
axum = "0.8"
base64.workspace = true
httpdate = "1"
clap.workspace = true
if-addrs = "0.13"
image = { version = "0.25", default-features = false, features = ["jpeg", "png"] }
lofty = "0.21"
quick-xml.workspace = true
rusqlite.workspace = true
serde.workspace = true
socket2 = { version = "0.5", features = ["all"] }
tokio = { version = "1", features = ["macros", "process", "rt-multi-thread", "net", "signal", "sync", "time"] }
toml.workspace = true
tower = { version = "0.5", features = ["util"] }
tower-http = { version = "0.6", features = ["fs", "trace"] }
tracing.workspace = true
tracing-subscriber.workspace = true
uuid.workspace = true
axum-server = { version = "0.7", features = ["tls-rustls-no-provider"] }
ring = "0.17"
rustls = { version = "0.23", default-features = false, features = ["ring", "std", "tls12", "logging"] }
