use std::path::Path;

use anyhow::Result;
use quick_xml::events::Event;
use quick_xml::Reader;

/// Fields a Kodi-style .nfo sidecar can override. Movie nfos use
/// <movie><title><year><genre>; episode nfos use <episodedetails> with
/// <showtitle><title><season><episode>.
#[derive(Debug, Default)]
pub struct NfoData {
    pub title: Option<String>,
    pub year: Option<i64>,
    pub genres: Vec<String>,
    pub directors: Vec<String>,
    pub rating: Option<f64>,
    pub plot: Option<String>,
    pub imdb_id: Option<String>,
    /// Movie set/collection (Kodi flat <set> form).
    pub set: Option<String>,
    pub show_title: Option<String>,
    pub season: Option<i64>,
    pub episode: Option<i64>,
}

/// Read the sidecar if it exists. Unparseable or missing files are simply
/// no data — the nfo is an optional enhancement, never a failure.
pub fn read_sidecar(media_path: &Path) -> Option<NfoData> {
    read_file(&media_path.with_extension("nfo"))
}

/// Read an .nfo by its own path (directory-level tvshow.nfo / season.nfo).
pub fn read_file(nfo_path: &Path) -> Option<NfoData> {
    let text = std::fs::read_to_string(nfo_path).ok()?;
    match parse(&text) {
        Ok(data) => Some(data),
        Err(err) => {
            tracing::warn!("ignoring malformed nfo {}: {err}", nfo_path.display());
            None
        }
    }
}

fn parse(text: &str) -> Result<NfoData> {
    let mut reader = Reader::from_str(text);
    reader.config_mut().trim_text(true);
    let mut data = NfoData::default();
    let mut current: Option<String> = None;
    let mut uniqueid_is_imdb = false;

    loop {
        match reader.read_event()? {
            Event::Start(e) => {
                let name = String::from_utf8_lossy(e.local_name().as_ref()).to_string();
                if name == "uniqueid" {
                    uniqueid_is_imdb = e
                        .try_get_attribute("type")
                        .ok()
                        .flatten()
                        .and_then(|a| a.unescape_value().ok())
                        .is_some_and(|v| v == "imdb");
                }
                current = Some(name);
            }
            Event::End(_) => current = None,
            Event::Text(t) => {
                let Some(element) = current.as_deref() else { continue };
                let value = t.unescape()?.trim().to_string();
                if value.is_empty() {
                    continue;
                }
                match element {
                    "title" => {
                        data.title.get_or_insert(value);
                    }
                    "showtitle" => {
                        data.show_title.get_or_insert(value);
                    }
                    "year" => {
                        data.year.get_or_insert(value.parse().unwrap_or(0));
                    }
                    // <season> in episode nfos, <seasonnumber> in Kodi's
                    // season.nfo — both name the season.
                    "season" | "seasonnumber" => {
                        data.season.get_or_insert(value.parse().unwrap_or(-1));
                    }
                    "episode" => {
                        data.episode.get_or_insert(value.parse().unwrap_or(-1));
                    }
                    "plot" => {
                        data.plot.get_or_insert(value);
                    }
                    "uniqueid" if uniqueid_is_imdb => {
                        data.imdb_id.get_or_insert(value);
                    }
                    "set" => {
                        data.set.get_or_insert(value);
                    }
                    "genre" => data.genres.push(value),
                    "director" => data.directors.push(value),
                    "rating" => {
                        if let Ok(rating) = value.parse::<f64>() {
                            data.rating.get_or_insert(rating);
                        }
                    }
                    _ => {}
                }
            }
            Event::Eof => break,
            _ => {}
        }
    }
    data.year = data.year.filter(|y| *y > 1800);
    data.season = data.season.filter(|s| *s >= 0);
    data.episode = data.episode.filter(|e| *e >= 0);
    Ok(data)
}

#[cfg(test)]
mod tests {
    use super::parse;

    #[test]
    fn parses_tvshow_nfo() {
        let data = parse(
            "<?xml version=\"1.0\"?>\n<!-- generated by media-enrich (TMDB) -->\n<tvshow>\n\
             <title>Fake Show</title>\n<plot>About things.</plot>\n<rating>8.7</rating>\n\
             <uniqueid type=\"imdb\">tt9999999</uniqueid>\n</tvshow>\n",
        )
        .unwrap();
        assert_eq!(data.title.as_deref(), Some("Fake Show"));
        assert_eq!(data.plot.as_deref(), Some("About things."));
        assert_eq!(data.rating, Some(8.7));
        assert_eq!(data.imdb_id.as_deref(), Some("tt9999999"));
    }

    #[test]
    fn parses_season_nfo() {
        let data = parse(
            "<season>\n<showtitle>Fake Show</showtitle>\n<seasonnumber>3</seasonnumber>\n\
             <plot>A season.</plot>\n</season>\n",
        )
        .unwrap();
        assert_eq!(data.show_title.as_deref(), Some("Fake Show"));
        assert_eq!(data.season, Some(3));
        assert_eq!(data.plot.as_deref(), Some("A season."));
    }
}
